/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaInterfaz;

import capaInterfaz.Componentes.ColorTabla;
import capaInterfaz.Componentes.RoundedPanel;
import capaInterfaz.Componentes.ComboMed;
import capaInterfaz.Componentes.MensajeMed;
import capaNegocio.clsComprobanteCompra;
import capaNegocio.clsDetalleCompra;
import capaNegocio.clsProducto;
import capaNegocio.clsProveedor;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.MatteBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author CMFerrer
 */
public class jdComprobanteCompra extends javax.swing.JDialog {

    clsProveedor objProv = new clsProveedor();
    clsProducto objProducto = new clsProducto();
    clsDetalleCompra objDetalle = new clsDetalleCompra();
    clsComprobanteCompra objCom = new clsComprobanteCompra();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private int posX = 0, posY = 0;
    ResultSet rsProducto;
    ArrayList listaDetalle = new ArrayList();
    private double precio;
    public String ruc;

    public jdComprobanteCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        getContentPane().setBackground(new Color(0, 0, 0, 0));
        getRootPane().setOpaque(false);
        setBackground(new Color(0, 0, 0, 0));
        jdcFechaCompra.setIcon(new ImageIcon(getClass().getResource("/Iconos/calendario.png")));
        jdcFechaCompra.getCalendarButton().setContentAreaFilled(false);
        jdcFechaCompra.setBackground(Color.WHITE);
        jdcFechaCompra.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
btnBusCompra.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
btnProv.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
btnProd.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
btnAñadir.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
btnQuitar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        cboComp.setUI(ComboMed.createUI(cboComp));
        tblCompras.getTableHeader().setDefaultRenderer(new ColorTabla());
        tblDetalle.getTableHeader().setDefaultRenderer(new ColorTabla());
        txtPrecio.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                actualizarDetalle();
            }

            public void removeUpdate(DocumentEvent e) {
                actualizarDetalle();
            }

            public void insertUpdate(DocumentEvent e) {
                actualizarDetalle();
            }

        });
    }

    private void setPrecio(Double precio) {
        this.precio = precio;
    }

    public Double getPrecio() {
        return this.precio;
    }
    
        public void alinearTabla(JTable tabla) {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        TableModel tableModel = tabla.getModel();

        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++) {
            tabla.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new RoundedPanel();
        botonMedGradiente1 = new capaInterfaz.Componentes.BotonMedGradiente();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        txtnumComprobante = new capaInterfaz.Componentes.TextoMed();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnumcompra = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jdcFechaCompra = new com.toedter.calendar.JDateChooser();
        btnBusCompra = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtProducto = new capaInterfaz.Componentes.TextoMed();
        jLabel16 = new javax.swing.JLabel();
        txtPrecio = new capaInterfaz.Componentes.TextoMed();
        txtTotal = new javax.swing.JLabel();
        btnNuevoPrveedor = new capaInterfaz.Componentes.BotonMedGradiente();
        botonMedGradiente2 = new capaInterfaz.Componentes.BotonMedGradiente();
        botonMedGradiente3 = new capaInterfaz.Componentes.BotonMedGradiente();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtruc = new capaInterfaz.Componentes.TextoMed();
        jLabel20 = new javax.swing.JLabel();
        cboComp = new javax.swing.JComboBox<>();
        txtRaz = new capaInterfaz.Componentes.TextoMed();
        jLabel21 = new javax.swing.JLabel();
        btnNuevaComprs = new capaInterfaz.Componentes.BotonMedGradiente();
        jsCantidad = new capaInterfaz.Componentes.spinnerMed();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnNuevoProducto = new capaInterfaz.Componentes.BotonMedGradiente();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnProv = new javax.swing.JLabel();
        btnProd = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JLabel();
        btnQuitar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMedGradiente1.setText("Modificar");
        botonMedGradiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMedGradiente1ActionPerformed(evt);
            }
        });
        jPanel2.add(botonMedGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 170, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel5.setText("BIOQUÍMICA DEL NORTE ANDINO S.A.C.  ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 13, -1, -1));

        jLabel8.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel8.setText("RUC: 20601834945 ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCompras.setRowHeight(24);
        tblCompras.setSelectionBackground(new java.awt.Color(16, 171, 131));
        tblCompras.setShowVerticalLines(false);
        tblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCompras);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 760, 170));

        txtnumComprobante.setText("");
        txtnumComprobante.setPlaceholder("");
        txtnumComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumComprobanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtnumComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 280, -1));

        jLabel9.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel9.setText("Chota-Cajamarca-Perú, Jr. San Martín N°477");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel10.setText("CORREO: bioquimicadelnorte@gmail.com");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 171, 131)));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel6.setText("COMPRA");

        jLabel7.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel7.setText("N°:");

        txtnumcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumcompraActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel15.setText("Fecha:");

        btnBusCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        btnBusCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBusCompraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnumcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBusCompra)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtnumcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addComponent(jdcFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBusCompra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 470, -1));

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel11.setText("Producto:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel12.setText("N° Comp:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel13.setText("Tipo Comp:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        txtProducto.setText("");
        txtProducto.setPlaceholder("");
        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });
        jPanel2.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 660, -1));

        jLabel16.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel16.setText("Cantidad:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        txtPrecio.setText("");
        txtPrecio.setPlaceholder("");
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 110, -1));

        txtTotal.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        txtTotal.setText("---------");
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 70, -1));

        btnNuevoPrveedor.setText("Nuevo Proveedor");
        btnNuevoPrveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPrveedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoPrveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, -1, -1));

        botonMedGradiente2.setText("Salir");
        jPanel2.add(botonMedGradiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 610, 170, -1));

        botonMedGradiente3.setText("Eliminar");
        botonMedGradiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMedGradiente3ActionPerformed(evt);
            }
        });
        jPanel2.add(botonMedGradiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 170, -1));

        jLabel18.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel18.setText("Precio:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel19.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel19.setText("Proveedor:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 166, -1, -1));

        txtruc.setText("");
        txtruc.setPlaceholder("");
        txtruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrucKeyTyped(evt);
            }
        });
        jPanel2.add(txtruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 164, 179, -1));

        jLabel20.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel20.setText("Razón social:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 166, -1, -1));

        cboComp.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        cboComp.setForeground(new java.awt.Color(51, 51, 51));
        cboComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleta", "Boleta Electrónica", "Factura", "Factura Electrónica" }));
        jPanel2.add(cboComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 190, -1));

        txtRaz.setText("");
        txtRaz.setPlaceholder("");
        txtRaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazActionPerformed(evt);
            }
        });
        jPanel2.add(txtRaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 164, 280, -1));

        jLabel21.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel21.setText("Total:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, -1, -1));

        btnNuevaComprs.setText("Nuevo");
        btnNuevaComprs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaComprsActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevaComprs, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 170, -1));
        jPanel2.add(jsCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDetalle.setRowHeight(24);
        tblDetalle.setSelectionBackground(new java.awt.Color(16, 171, 131));
        tblDetalle.setShowVerticalLines(false);
        tblDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDetalle);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 530, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ICONO.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 130));

        btnNuevoProducto.setText("Nuevo Producto");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, -1, -1));

        btnProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        btnProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProvMouseClicked(evt);
            }
        });
        jPanel2.add(btnProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        btnProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        btnProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdMouseClicked(evt);
            }
        });
        jPanel2.add(btnProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, -1, -1));

        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mas.png"))); // NOI18N
        btnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAñadirMouseClicked(evt);
            }
        });
        jPanel2.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/menos.png"))); // NOI18N
        btnQuitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitarMouseClicked(evt);
            }
        });
        jPanel2.add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1090, 740));

        jPanel1.setBackground(new java.awt.Color(16, 171, 131));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIONAR COMPRA");

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusable(false);
        btnSalir.setPreferredSize(new java.awt.Dimension(49, 25));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit (2)_1.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(344, 344, 344)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 158));
        jPanel1.setBorder(BorderFactory.createMatteBorder(3, 3, 0, 3, Color.GRAY));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1220, 700));
        jPanel3.setBorder(BorderFactory.createMatteBorder(0, 3, 3, 3, Color.GRAY));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_formMouseDragged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
public void quitar(){
   for (int i = 0; i < listaDetalle.size(); i++) {
            Object[] datos = (Object[]) listaDetalle.get(i);
            if (datos[0].equals(txtProducto.getText())) {
                listaDetalle.remove(i);
                new MensajeMed().mostrar(this, "Producto eliminado correctamente", 2);
                listarDetalle(listaDetalle);
            }

        }
        actualizarTotal();
        
        if (tblDetalle.getRowCount() == 0) {
            txtTotal.setText("");
        }  
}
    private void txtnumcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumcompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumcompraActionPerformed

    private void txtnumComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumComprobanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumComprobanteActionPerformed
private void buscarProv(){
     ResultSet rsPr = null;

        try {
            if (txtruc.getText().isEmpty()) {
                new MensajeMed().mostrar(this, "Ingrese ruc a buscar...",0);
                txtruc.requestFocus();
            } else {
                
                 rsPr = objProv.buscarProv(txtruc.getText());
                if (rsPr.next()) {
                    if (objProv.validarVigencia(txtruc.getText())) {
                    txtRaz.setText(rsPr.getString("razonsocial"));
}else{int rpta = new MensajeMed().mostrar(this, "Proveedor inactivo, desea activarlo?", 1);
                    if (rpta == JOptionPane.YES_OPTION) {
                objProv.actualizarestado(txtruc.getText()); 
                  txtRaz.setText(rsPr.getString("razonsocial"));
                new MensajeMed().mostrar(this, "Se activó correctamente", 2);
                    }else{
                               txtruc.requestFocus(); 
                    }
  
                }
                } else {
                    new MensajeMed().mostrar(this, "Ruc no registrado...",0);
                    btnNuevoPrveedor.requestFocus();
                }   
                
                
            }
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }         
    }
    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void btnNuevoPrveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPrveedorActionPerformed
        // TODO add your handling code here:
        jdManProveedor obj = new jdManProveedor(null, true);
        try {
            obj.ruc = txtruc.getText();
            obj.setVisible(true);
            ruc = txtruc.getText();
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }
    }//GEN-LAST:event_btnNuevoPrveedorActionPerformed
private String obtenerTipoComprobante() {
        
        String tipo[] = cboComp.getSelectedItem().toString().split(" ");
        if (tipo.length > 1) {
            return (tipo[0].substring(0, 1) + tipo[1].substring(0, 1));
        } else {
            return tipo[0].substring(0, 1);
            
        }
    }
    private void botonMedGradiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMedGradiente1ActionPerformed
         // TODO add your handling code here:
         try {
            Integer numCompra = Integer.parseInt(txtnumcompra.getText());
            ResultSet rsVentaTemporal = objCom.buscarCompra(numCompra);
            ArrayList detalleEliminar = datosDetalle(objDetalle.listarDetalle(numCompra));
            objCom.modificarComprobanteCompra(Integer.parseInt(txtnumcompra.getText()),
                    txtnumComprobante.getText(),
                    obtenerTipoComprobante(),
                    Double.parseDouble(txtTotal.getText()),
                    sdf.format(jdcFechaCompra.getDate()),
                    txtruc.getText(),
                    
                    detalleEliminar,
                    listaDetalle);
            new MensajeMed().mostrar(this, "Se modificó correctamente", 2);
            
            listarCompras();
            limpirDetalle();
            
        } catch (Exception ex) {
            new MensajeMed().mostrar(this, ex.getMessage(),3);
        }
    }//GEN-LAST:event_botonMedGradiente1ActionPerformed

    private void txtRazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazActionPerformed

    private void btnNuevaComprsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaComprsActionPerformed
        // TODO add your handling code here:
        try {
            if (btnNuevaComprs.getText().equals("Nuevo")) {
                btnNuevaComprs.setText("Guardar");
                txtnumcompra.setText(objCom.generarCodigoCCompra().toString());

            } else {
                btnNuevaComprs.setText("Nuevo");
                //Guardar 
                objCom.registrarCompraTran(Integer.parseInt(txtnumcompra.getText()),
                        txtnumComprobante.getText(),
                        obtenerTipoComprobante(),
                        Double.parseDouble(txtTotal.getText()),
                        sdf.format(jdcFechaCompra.getDate()),
                        txtruc.getText(),
                        listaDetalle);
                new MensajeMed().mostrar(this, "Se registró correctamente.", 2);
                listarCompras();
                limpiarVenta();
                limpirDetalle();
            }

        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }
    }//GEN-LAST:event_btnNuevaComprsActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed
private void buscarProdu(){
      try {
            jdBuscarProductosCompra objFrmBuscar = new jdBuscarProductosCompra(null, true);
            objFrmBuscar.setVisible(true);
//            txtProducto.setText(objFrmBuscar.codigo +" "+objFrmBuscar.producto);
            txtProducto.setText(objFrmBuscar.producto);
            rsProducto = objFrmBuscar.rsProducto;
            if (objFrmBuscar.rsProducto.next()) {
                jsCantidad.setCantidad(1);
                setPrecio(objFrmBuscar.rsProducto.getDouble("preciocompra"));
                txtPrecio.setText(String.valueOf(objFrmBuscar.rsProducto.getDouble("preciocompra")));

            }
            jsCantidad.setPrecio(txtPrecio, precio);

        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }        
    }

private void anadir(){
     try {

            if (validarDetalle(txtProducto.getText())) {
                Object producto[] = new Object[5];

                producto[0] = rsProducto.getString("nombre");
                producto[1] = rsProducto.getDouble("preciocompra");
                producto[2] = jsCantidad.getCantidad();
                producto[3] = rsProducto.getDouble("preciocompra") * jsCantidad.getCantidad();
                producto[4] = rsProducto.getInt("codproducto");
                listaDetalle.add(producto);
                listarDetalle(listaDetalle);
                actualizarTotal();


            } else {
                new MensajeMed().mostrar(this, "El producto ya se encuentre en la compra",3);

            }

        } catch (Exception ex) {
            new MensajeMed().mostrar(this, ex.getMessage(),3);
        }
}
    private void txtrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c = evt.getKeyChar();//metodo solo para ingresar numeros
        if (c < '0' || c > '9') {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        //metodo solo para ingresar numeros
        if (txtruc.getText().length() == 11) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtrucKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        listarCompras();
    }//GEN-LAST:event_formWindowOpened

    private void tblComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprasMouseClicked
        // TODO add your handling code here:
        txtnumcompra.setText(String.valueOf(tblCompras.getValueAt(tblCompras.getSelectedRow(), 0)));
        buscarCom();
    }//GEN-LAST:event_tblComprasMouseClicked

    private void tblDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleMouseClicked
        // TODO add your handling code here:
        txtProducto.setText(String.valueOf(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 0)));
            jsCantidad.setCantidad(Integer.parseInt(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 2).toString()));
            txtPrecio.setText(String.valueOf(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 3)));
            jsCantidad.setPrecio(txtPrecio,Double.parseDouble(txtPrecio.getText())/jsCantidad.getCantidad());
            
        
    }//GEN-LAST:event_tblDetalleMouseClicked

    private void buscarCom(){
             ResultSet rsCompra = null;
         ResultSet rsDetalle = null;
         
     
        try {
            if (txtnumcompra.getText().equals("")) {
                new MensajeMed().mostrar(this, "Ingrese el número de compra a buscar!",0);
            } else {
                rsCompra = objCom.buscarCompra(Integer.parseInt(txtnumcompra.getText()));
                rsDetalle=objDetalle.listarDetalle(Integer.parseInt(txtnumcompra.getText()));
                listaDetalle = datosDetalle(objDetalle.listarDetalle(Integer.parseInt(txtnumcompra.getText())));
                if (rsCompra.next()) {
                    listarDetalle(listaDetalle);
                    jdcFechaCompra.setDate(rsCompra.getDate("fecha"));
                    txtRaz.setText(rsCompra.getString("razonSocial"));
                    txtruc.setText(rsCompra.getString("rucproveedor"));
                    txtnumComprobante.setText(rsCompra.getString("numcomprobante"));
                    txtTotal.setText(rsCompra.getString("total"));

                    
                    if (rsCompra.getString("tipo").equals("B")) {
                    cboComp.setSelectedIndex(0);
                    
                } else if (rsCompra.getString("tipo").equals("BE")) {
                    cboComp.setSelectedIndex(1);
                    
                } else if (rsCompra.getString("tipo").equals("F")) {
                    cboComp.setSelectedIndex(2);
                    
                } else {
                    cboComp.setSelectedIndex(3);
                    
                }

                    
                } else {
                    new MensajeMed().mostrar(this, "Número de comprobante no existe!",0);
                    limpiarVenta();
                }
            }
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }  
    }
    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        // TODO add your handling code here:
        jdGestionarProducto obj = new jdGestionarProducto(null, true);
        obj.setVisible(true);
    }//GEN-LAST:event_btnNuevoProductoActionPerformed
public ArrayList datosDetalle(ResultSet rsDetalle) {
        ArrayList detalle = new ArrayList();
        
        try {
            while (rsDetalle.next()) {
                Object detalleDatos[] = new Object[5];
                detalleDatos[0] = rsDetalle.getString("producto");
                detalleDatos[1] = rsDetalle.getDouble("precio");
                detalleDatos[2] = rsDetalle.getInt("cantidad");
                detalleDatos[3] = rsDetalle.getDouble("precio") * rsDetalle.getInt("cantidad");
                detalleDatos[4] = rsDetalle.getInt("codproducto");
                detalle.add(detalleDatos);
                
            }
        } catch (Exception e) {
        }
        return detalle;
    }
    private void botonMedGradiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMedGradiente3ActionPerformed
         // TODO add your handling code here:
         try {
            int rpta = new MensajeMed().mostrar(this, "Está seguro de eliminar la compra seleccionada",1);
            if (rpta == JOptionPane.YES_OPTION) {
                if (!txtnumcompra.getText().isEmpty()) {
                    objCom.eliminarComprobanteCompra(Integer.parseInt(txtnumcompra.getText()), datosDetalle(objDetalle.listarDetalle(Integer.parseInt(txtnumcompra.getText()))));
                    new MensajeMed().mostrar(this, "Se ha eliminado la compra correctamente",2);
                    limpiarVenta();
                    limpirDetalle();
                    
                    
                } else {
                    new MensajeMed().mostrar(this, "Por favor ingrese el número de venta a eliminar",1);
                    
                }
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_botonMedGradiente3ActionPerformed

    private void btnBusCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusCompraMouseClicked
          // TODO add your handling code here:
         buscarCom();
    }//GEN-LAST:event_btnBusCompraMouseClicked

    private void btnProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdMouseClicked
         // TODO add your handling code here:
         buscarProdu();
    }//GEN-LAST:event_btnProdMouseClicked

    private void btnProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProvMouseClicked
         // TODO add your handling code here:
         buscarProv();
    }//GEN-LAST:event_btnProvMouseClicked

    private void btnAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirMouseClicked
        // TODO add your handling code here:
        anadir();
    }//GEN-LAST:event_btnAñadirMouseClicked

    private void btnQuitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitarMouseClicked
         // TODO add your handling code here:
        quitar();
    }//GEN-LAST:event_btnQuitarMouseClicked
    public void actualizarTotal() {
        Double total = 0.0;
        for (int i = 0; i < tblDetalle.getRowCount(); i++) {
            total += (Double) tblDetalle.getValueAt(i, 3);
            txtTotal.setText(total.toString());

        }
    }

   public void listarDetalle(ResultSet rsDetalle) {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
//        modelo.addColumn("Cod.");
            modelo.addColumn("Producto");
            modelo.addColumn("Precio");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Subtotal");
//            listaDetalle = new ArrayList();
            while (rsDetalle.next()) {
                Object detalleDatos[] = new Object[5];

//                detalleDatos[0] = rsDetalle.getString("producto");
//                detalleDatos[1] = rsDetalle.getDouble("precio");
//                detalleDatos[2] = rsDetalle.getInt("cantidad");
//                detalleDatos[3] = rsDetalle.getDouble("precio") * rsDetalle.getInt("cantidad");
//                detalleDatos[4] = rsDetalle.getInt("codproducto");
//                listaDetalle.add(detalleDatos);
                modelo.addRow(new Object[]{
                    rsDetalle.getString("producto"),
                    rsDetalle.getDouble("precio"),
                    rsDetalle.getInt("cantidad"),
                    rsDetalle.getDouble("precio") * rsDetalle.getInt("cantidad"),});
                
            }
            
            tblDetalle.setModel(modelo);
        } catch (Exception e) {
        }
        
    }

    public void listarDetalle(ArrayList lista) {
        DefaultTableModel modelo = new DefaultTableModel();
//        modelo.addColumn("Cod.");
        modelo.addColumn("Producto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Subtotal");
        Object[] datos = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            datos = (Object[]) lista.get(i);
            modelo.addRow(datos);

        }

        tblDetalle.setModel(modelo);
        alinearTabla(tblDetalle);
    }

    public void actualizarDetalle() {
//        System.out.println(txtProducto.getText().split(" ")[0]);

        for (int i = 0; i < tblDetalle.getRowCount(); i++) {
            for (int j = 0; j < tblDetalle.getColumnCount(); j++) {
                if (tblDetalle.getModel().getValueAt(i, j).equals(txtProducto.getText())) {
                    tblDetalle.setValueAt(jsCantidad.getCantidad(), i, j + 2);
                    Object[] datos = (Object[]) listaDetalle.get(i);
                    datos[2] = jsCantidad.getCantidad();
                    Double precio = (Double) tblDetalle.getModel().getValueAt(i, j + 1);
                    tblDetalle.setValueAt(jsCantidad.getCantidad() * precio, i, j + 3);
                   
                    datos[3] = tblDetalle.getModel().getValueAt(i, j + 3);

                }
            }
        }
        listarDetalle(listaDetalle);
        actualizarTotal();
    }

    public Boolean validarDetalle(String producto) {
        for (int i = 0; i < listaDetalle.size(); i++) {
            Object[] datos = (Object[]) listaDetalle.get(i);
            if (datos[0].equals(producto)) {
                return false;
            }
        }
        return true;
    }

    public void limpiarVenta() {
        jdcFechaCompra.setDate(null);
        txtnumcompra.setText("");
        txtnumComprobante.setText("");
        txtRaz.setText("");
        txtruc.setText("");
        txtProducto.setText("");
    }

    public void limpirDetalle() {
        txtPrecio.setText("");
        jsCantidad.setCantidad(1);
        txtTotal.setText("---------");
       listaDetalle= new ArrayList();
        listarDetalle(listaDetalle);
        
    }
    
 

    public void listarCompras() {
        ResultSet rsLista = null;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nro");
        model.addColumn("Nro Comprobante");
        model.addColumn("Tipo");
        model.addColumn("Total");
        model.addColumn("Fecha");
        model.addColumn("Proveedor");
        String tipo;
        tblCompras.setModel(model);
        try {
            rsLista = objCom.listarComprobanteCompra();
            while (rsLista.next()) {
                tipo = rsLista.getString("tipo"); //D,O,M
                if (tipo.equals("B")) {
                    tipo = "Boleta";
                }
                if (tipo.equals("BE")) {
                    tipo = "Boleta Electrónica";
                }
                if (tipo.equals("F")) {
                    tipo = "Factura";
                }
                if (tipo.equals("FE")) {
                    tipo = "Factura Electrónica";
                }
                model.addRow(new Object[]{
                    rsLista.getInt("codcomprobante"),
                    rsLista.getString("numcomprobante"),
                    tipo,
                    rsLista.getDouble("total"),
                    rsLista.getDate("fecha"),
                    rsLista.getString("razonsocial")

                });

            }
            alinearTabla(tblCompras);
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdComprobanteCompra dialog = new jdComprobanteCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private capaInterfaz.Componentes.BotonMedGradiente botonMedGradiente1;
    private capaInterfaz.Componentes.BotonMedGradiente botonMedGradiente2;
    private capaInterfaz.Componentes.BotonMedGradiente botonMedGradiente3;
    private javax.swing.JLabel btnAñadir;
    private javax.swing.JLabel btnBusCompra;
    private capaInterfaz.Componentes.BotonMedGradiente btnNuevaComprs;
    private capaInterfaz.Componentes.BotonMedGradiente btnNuevoProducto;
    private capaInterfaz.Componentes.BotonMedGradiente btnNuevoPrveedor;
    private javax.swing.JLabel btnProd;
    private javax.swing.JLabel btnProv;
    private javax.swing.JLabel btnQuitar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboComp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcFechaCompra;
    private capaInterfaz.Componentes.spinnerMed jsCantidad;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTable tblDetalle;
    private capaInterfaz.Componentes.TextoMed txtPrecio;
    private capaInterfaz.Componentes.TextoMed txtProducto;
    private capaInterfaz.Componentes.TextoMed txtRaz;
    private javax.swing.JLabel txtTotal;
    private capaInterfaz.Componentes.TextoMed txtnumComprobante;
    private javax.swing.JTextField txtnumcompra;
    private capaInterfaz.Componentes.TextoMed txtruc;
    // End of variables declaration//GEN-END:variables
}
