/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaInterfaz;

import capaInterfaz.Componentes.ColorTabla;
import capaInterfaz.Componentes.RoundedPanel;
import capaInterfaz.Componentes.ComboMed;
import capaNegocio.clsComprobanteCompra;
import capaNegocio.clsDetalleCompra;
import capaNegocio.clsProducto;
import capaNegocio.clsProveedor;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CMFerrer
 */
public class jdComprobanteCompra extends javax.swing.JDialog {
    clsProveedor objProv =new clsProveedor();
    clsProducto objProducto=new clsProducto();
    clsDetalleCompra objDetalle =new clsDetalleCompra();
    clsComprobanteCompra objCom=new clsComprobanteCompra();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private int posX = 0, posY = 0;
    ResultSet rsProducto;
    ArrayList listaDetalle = new ArrayList();
    private double precio;
    public String ruc;
    public jdComprobanteCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        getContentPane().setBackground(new Color(0, 0, 0, 0));
        getRootPane().setOpaque(false);
        setBackground(new Color(0, 0, 0, 0));
        
        cboComp.setUI(ComboMed.createUI(cboComp));
        tblCompras.getTableHeader().setDefaultRenderer(new ColorTabla());
        tblDetalle.getTableHeader().setDefaultRenderer(new ColorTabla());
        txtPrecio.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                actualizarDetalle();
            }

            public void removeUpdate(DocumentEvent e) {
                actualizarDetalle();
            }

            public void insertUpdate(DocumentEvent e) {
                actualizarDetalle();
            }

        });
    }
  private void setPrecio(Double precio) {
        this.precio = precio;
    }

    public Double getPrecio() {
        return this.precio;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new RoundedPanel();
        btnMenos = new capaInterfaz.Componentes.BotonMedGradiente();
        botonMedGradiente1 = new capaInterfaz.Componentes.BotonMedGradiente();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        txtnumComprobante = new capaInterfaz.Componentes.TextoMed();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnumcompra = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jdcFechaCompra = new com.toedter.calendar.JDateChooser();
        btnBuscarCom = new capaInterfaz.Componentes.BotonMedGradiente();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtProducto = new capaInterfaz.Componentes.TextoMed();
        btnBuscarProv = new capaInterfaz.Componentes.BotonMedGradiente();
        jLabel16 = new javax.swing.JLabel();
        txtPrecio = new capaInterfaz.Componentes.TextoMed();
        txtTotal = new javax.swing.JLabel();
        btnNuevoPrveedor = new capaInterfaz.Componentes.BotonMedGradiente();
        botonMedGradiente2 = new capaInterfaz.Componentes.BotonMedGradiente();
        botonMedGradiente3 = new capaInterfaz.Componentes.BotonMedGradiente();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtruc = new capaInterfaz.Componentes.TextoMed();
        jLabel20 = new javax.swing.JLabel();
        cboComp = new javax.swing.JComboBox<>();
        txtRaz = new capaInterfaz.Componentes.TextoMed();
        jLabel21 = new javax.swing.JLabel();
        btnNuevaComprs = new capaInterfaz.Componentes.BotonMedGradiente();
        jsCantidad = new capaInterfaz.Componentes.spinnerMed();
        btnMas = new capaInterfaz.Componentes.BotonMedGradiente();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new capaInterfaz.Componentes.BotonMedGradiente();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });
        jPanel2.add(btnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 50, -1));

        botonMedGradiente1.setText("Modificar");
        botonMedGradiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMedGradiente1ActionPerformed(evt);
            }
        });
        jPanel2.add(botonMedGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 160, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel5.setText("BIOQUÍMICA DEL NORTE ANDINO S.A.C.  ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 13, -1, -1));

        jLabel8.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel8.setText("RUC: 20601834945 ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCompras.setSelectionBackground(new java.awt.Color(104, 228, 176));
        tblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCompras);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 760, 170));

        txtnumComprobante.setText("");
        txtnumComprobante.setPlaceholder("");
        txtnumComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumComprobanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtnumComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 317, -1));

        jLabel9.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel9.setText("Chota-Cajamarca-Perú, Jr. San Martín N°477");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel10.setText("CORREO: bioquimicadelnorte@gmail.com");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel6.setText("COMPRA");

        jLabel7.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel7.setText("N°:");

        txtnumcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumcompraActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel15.setText("Fecha:");

        btnBuscarCom.setText("B");
        btnBuscarCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarComActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnumcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarCom, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtnumcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(btnBuscarCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdcFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 470, -1));

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel11.setText("Producto:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel12.setText("N° Comp:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel13.setText("Tipo Comp:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        txtProducto.setText("");
        txtProducto.setPlaceholder("");
        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });
        jPanel2.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 750, -1));

        btnBuscarProv.setText("B");
        btnBuscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProvActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 162, 57, -1));

        jLabel16.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel16.setText("Cantidad:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        txtPrecio.setText("");
        txtPrecio.setPlaceholder("");
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 110, -1));

        txtTotal.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        txtTotal.setText("---------");
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 70, -1));

        btnNuevoPrveedor.setText("Nuevo");
        btnNuevoPrveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPrveedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoPrveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 162, -1, -1));

        botonMedGradiente2.setText("Salir");
        jPanel2.add(botonMedGradiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 610, 160, -1));

        botonMedGradiente3.setText("Eliminar");
        jPanel2.add(botonMedGradiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 160, -1));

        jLabel18.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel18.setText("Precio:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel19.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel19.setText("Proveedor:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 166, -1, -1));

        txtruc.setText("");
        txtruc.setPlaceholder("");
        txtruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrucKeyTyped(evt);
            }
        });
        jPanel2.add(txtruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 164, 179, -1));

        jLabel20.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel20.setText("Razón social:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 166, -1, -1));

        cboComp.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        cboComp.setForeground(new java.awt.Color(51, 51, 51));
        cboComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleta", "Boleta Electrónica", "Factura", "Factura Electrónica" }));
        jPanel2.add(cboComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 190, -1));

        txtRaz.setText("");
        txtRaz.setPlaceholder("");
        txtRaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazActionPerformed(evt);
            }
        });
        jPanel2.add(txtRaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 164, 317, -1));

        jLabel21.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel21.setText("Total:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, -1, -1));

        btnNuevaComprs.setText("Nuevo");
        btnNuevaComprs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaComprsActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevaComprs, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 157, -1));
        jPanel2.add(jsCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });
        jPanel2.add(btnMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 50, -1));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDetalle.setSelectionBackground(new java.awt.Color(104, 228, 176));
        tblDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDetalle);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 530, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ICONO.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 130));

        btnBuscar.setText("B");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 57, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1070, 740));

        jPanel1.setBackground(new java.awt.Color(84, 248, 147));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIONAR COMPRA");

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusable(false);
        btnSalir.setPreferredSize(new java.awt.Dimension(49, 25));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit (2)_1.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(408, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(344, 344, 344)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 158));
        jPanel1.setBorder(BorderFactory.createMatteBorder(3, 3, 0, 3, Color.GRAY));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1190, 700));
        jPanel3.setBorder(BorderFactory.createMatteBorder(0, 3, 3, 3, Color.GRAY));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        posX = evt.getX();
	posY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_formMouseDragged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // TODO add your handling code here:
         for (int i = 0; i < listaDetalle.size(); i++) {
            Object[] datos = (Object[]) listaDetalle.get(i);
            if (datos[0].equals(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 0))) {
                listaDetalle.remove(i);
                JOptionPane.showMessageDialog(this, "Producto eliminado correctamente");
                listarDetalle(listaDetalle);
            }
        }
    }//GEN-LAST:event_btnMenosActionPerformed

    private void txtnumcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumcompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumcompraActionPerformed

    private void txtnumComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumComprobanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumComprobanteActionPerformed

    private void btnBuscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProvActionPerformed
        // TODO add your handling code here:
        ResultSet rsPr = null;
   
        try {
            if(txtruc.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese ruc a buscar...");
                txtruc.requestFocus();
            }else{
                rsPr=objProv.buscarProv(txtruc.getText());
                if(rsPr.next()){
                    txtRaz.setText(rsPr.getString("razonsocial"));
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Ruc no registrado...");
                    btnNuevoPrveedor.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarProvActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void btnNuevoPrveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPrveedorActionPerformed
        // TODO add your handling code here:
        jdManProveedor obj = new jdManProveedor(null, true);
        try {
            obj.ruc=txtruc.getText();
          obj.setVisible(true);
        ruc=txtruc.getText();   
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnNuevoPrveedorActionPerformed

    private void botonMedGradiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMedGradiente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMedGradiente1ActionPerformed

    private void txtRazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazActionPerformed

    private void btnNuevaComprsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaComprsActionPerformed
        // TODO add your handling code here:
         try {
            if (btnNuevaComprs.getText().equals("Nuevo")) {
                btnNuevaComprs.setText("Guardar");
                txtnumcompra.setText(objCom.generarCodigoCCompra().toString());

            } else {
                btnNuevaComprs.setText("Nuevo");
                //Guardar 
                objCom.registrarCompraTran(Integer.parseInt(txtnumcompra.getText()),
                    txtnumComprobante.getText(),
                    cboComp.getSelectedItem().toString().substring(0, 1),
                    Double.parseDouble(txtTotal.getText()),
                    sdf.format(jdcFechaCompra.getDate()),
                    txtruc.getText(),
                    listaDetalle);
                listarCompras();
limpiarVenta();
limpirDetalle();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnNuevaComprsActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
          try {
            jdBuscarProductos objFrmBuscar = new jdBuscarProductos(null, true);
            objFrmBuscar.setVisible(true);
//            txtProducto.setText(objFrmBuscar.codigo +" "+objFrmBuscar.producto);
            txtProducto.setText(objFrmBuscar.producto);
            rsProducto = objFrmBuscar.rsProducto;
            if (objFrmBuscar.rsProducto.next()) {
                jsCantidad.setCantidad(1);
                setPrecio(objFrmBuscar.rsProducto.getDouble("preciocompra"));
                txtPrecio.setText(String.valueOf(objFrmBuscar.rsProducto.getDouble("preciocompra")));

            }
            jsCantidad.setPrecio(txtPrecio, precio);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        // TODO add your handling code here:
        try {

            if (validarDetalle(txtProducto.getText())) {
                Object producto[] = new Object[5];

                producto[0] = rsProducto.getString("nombre");
                producto[1] = rsProducto.getDouble("preciocompra");
                producto[2] = jsCantidad.getCantidad();
                producto[3] = rsProducto.getDouble("preciocompra") * jsCantidad.getCantidad();      
                producto[4] = rsProducto.getInt("codproducto");
                listaDetalle.add(producto);
                listarDetalle(listaDetalle);
                actualizarTotal();
//                txtTotal.setText(String.valueOf(rsProducto.getDouble("precioventa") * jsCantidad.getCantidad()));
//                txtIGV.setText(String.valueOf(Double.parseDouble(txtTotal.getText()) * 0.18));
//                txtSubTotal.setText(String.valueOf(Double.parseDouble(txtTotal.getText()) - Double.parseDouble(txtIGV.getText())));

            } else {
                JOptionPane.showMessageDialog(this, "El producto ya se encuentre en la compra");

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnMasActionPerformed

    private void txtrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c = evt.getKeyChar();//metodo solo para ingresar numeros
        if (c < '0' || c > '9') {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        //metodo solo para ingresar numeros
        if (txtruc.getText().length() == 11) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtrucKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        listarCompras();
    }//GEN-LAST:event_formWindowOpened

    private void tblComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblComprasMouseClicked

    private void tblDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleMouseClicked
        // TODO add your handling code here:
        txtProducto.setText(String.valueOf(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 0)));
        jsCantidad.setCantidad((Integer) (tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 2)));
        txtPrecio.setText(String.valueOf(tblDetalle.getValueAt(tblDetalle.getSelectedRow(), 3)));
    }//GEN-LAST:event_tblDetalleMouseClicked

    private void btnBuscarComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarComActionPerformed
        // TODO add your handling code here:
        ResultSet rsLista=null;
       String tipo="";
        try {
            if(txtnumcompra.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Ingrese el número de compra a buscar!");
            }else{
                rsLista=objCom.buscarCompra(Integer.parseInt(txtnumcompra.getText()));
                if (rsLista.next()){
                    jdcFechaCompra.setDate(rsLista.getDate("fecha"));
                    txtRaz.setText(rsLista.getString("razonSocial"));
                    txtnumComprobante.setText(rsLista.getString("numcomprobante"));
                    txtTotal.setText(rsLista.getString("total"));
                    
                    tipo=rsLista.getString("tipo");
                    if(tipo.equals("B")) cboComp.setSelectedItem("Boleta");
                    if(tipo.equals("BE")) cboComp.setSelectedItem("Boleta Electrónica");
                    if(tipo.equals("F")) cboComp.setSelectedItem("Factura");
                    if(tipo.equals("FE")) cboComp.setSelectedItem("Factura Electrónica");
                    
                    listarDetalle2(Integer.parseInt(txtnumcompra.getText()));
                }else{
                    JOptionPane.showMessageDialog(this, "Número de hbaitación no existe!");
                    limpiarVenta();
                }
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnBuscarComActionPerformed
 public void actualizarTotal() {
        Double total = 0.0;
        for (int i = 0; i < tblDetalle.getRowCount(); i++) {
            total += (Double) tblDetalle.getValueAt(i, 3);
            txtTotal.setText(total.toString());
            
        }
    }
 public void listarDetalle2(Integer cod) {
                  ResultSet rsLista = null;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Producto");
        model.addColumn("Precio");
        model.addColumn("Cantidad");
        model.addColumn("Subtotal");
        
  
        tblDetalle.setModel(model);
        try {
            Double sub=0.0;
            rsLista = objDetalle.listarDetalle(cod);
            while (rsLista.next()) {
                sub=rsLista.getDouble("precio")*rsLista.getInt("cantidad");
                model.addRow(new Object[]{
                    rsLista.getString("producto"),
                    rsLista.getDouble("precio"),
                    rsLista.getInt("cantidad"),
                    sub
                });

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
 public void listarDetalle(ArrayList lista) {
        DefaultTableModel modelo = new DefaultTableModel();
//        modelo.addColumn("Cod.");
        modelo.addColumn("Producto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Subtotal");
        Object[] datos = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            datos = (Object[]) lista.get(i);
            modelo.addRow(datos);

        }

        tblDetalle.setModel(modelo);

    }
    public void actualizarDetalle() {
//        System.out.println(txtProducto.getText().split(" ")[0]);

        for (int i = 0; i < tblDetalle.getRowCount(); i++) {
            for (int j = 0; j < tblDetalle.getColumnCount(); j++) {
                if (tblDetalle.getModel().getValueAt(i, j).equals(txtProducto.getText())) {
                    tblDetalle.setValueAt(jsCantidad.getCantidad(), i, j + 2);
                    Object[] datos = (Object[]) listaDetalle.get(i);
                    datos[2] = jsCantidad.getCantidad();
                    Double precio = (Double) tblDetalle.getModel().getValueAt(i, j + 1);
                    tblDetalle.setValueAt(jsCantidad.getCantidad() * precio, i, j + 3);
                                        datos[3] = jsCantidad.getCantidad();
                    datos[3] = tblDetalle.getModel().getValueAt(i, j + 3);


                }
            }
        }
        listarDetalle(listaDetalle);
        actualizarTotal();
    }

    public Boolean validarDetalle(String producto) {
        for (int i = 0; i < listaDetalle.size(); i++) {
            Object[] datos = (Object[]) listaDetalle.get(i);
            if (datos[0].equals(producto)) {
                return false;
            }
        }
        return true;
    }
    public void limpiarVenta(){
        jdcFechaCompra.setDate(null);
        txtnumcompra.setText("");
        txtnumComprobante.setText("");
        txtRaz.setText("");
        txtruc.setText("");
        txtProducto.setText("");
           }
    public void limpirDetalle(){
        txtPrecio.setText("");
        jsCantidad.setCantidad(1);
    }
     public void listarCompras() {
        ResultSet rsLista = null;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nro");
        model.addColumn("Nro Comprobante");
        model.addColumn("Tipo");
        model.addColumn("Total");
        model.addColumn("Fecha");
        model.addColumn("Proveedor");
       String tipo;
        tblCompras.setModel(model);
        try {
            rsLista = objCom.listarComprobanteCompra();
            while (rsLista.next()) {
                tipo=rsLista.getString("tipo"); //D,O,M
                if (tipo.equals("B")) tipo="Boleta";
                if (tipo.equals("BE")) tipo="Boleta Electrónica";
                if (tipo.equals("F")) tipo="Factura";
                                if (tipo.equals("FE")) tipo="Factura Electrónica";
                model.addRow(new Object[]{
                    rsLista.getInt("codcomprobante"),
                    rsLista.getString("numcomprobante"),
                    tipo,
                    
                    rsLista.getDouble("total"),
                    rsLista.getDate("fecha"),
                    rsLista.getString("razonsocial")

                });

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdComprobanteCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdComprobanteCompra dialog = new jdComprobanteCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private capaInterfaz.Componentes.BotonMedGradiente botonMedGradiente1;
    private capaInterfaz.Componentes.BotonMedGradiente botonMedGradiente2;
    private capaInterfaz.Componentes.BotonMedGradiente botonMedGradiente3;
    private capaInterfaz.Componentes.BotonMedGradiente btnBuscar;
    private capaInterfaz.Componentes.BotonMedGradiente btnBuscarCom;
    private capaInterfaz.Componentes.BotonMedGradiente btnBuscarProv;
    private capaInterfaz.Componentes.BotonMedGradiente btnMas;
    private capaInterfaz.Componentes.BotonMedGradiente btnMenos;
    private capaInterfaz.Componentes.BotonMedGradiente btnNuevaComprs;
    private capaInterfaz.Componentes.BotonMedGradiente btnNuevoPrveedor;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboComp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcFechaCompra;
    private capaInterfaz.Componentes.spinnerMed jsCantidad;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTable tblDetalle;
    private capaInterfaz.Componentes.TextoMed txtPrecio;
    private capaInterfaz.Componentes.TextoMed txtProducto;
    private capaInterfaz.Componentes.TextoMed txtRaz;
    private javax.swing.JLabel txtTotal;
    private capaInterfaz.Componentes.TextoMed txtnumComprobante;
    private javax.swing.JTextField txtnumcompra;
    private capaInterfaz.Componentes.TextoMed txtruc;
    // End of variables declaration//GEN-END:variables
}
