/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaInterfaz;

import capaInterfaz.Componentes.ColorTabla;
import capaInterfaz.Componentes.RoundedPanel;
import capaInterfaz.Componentes.ComboMed;
import capaInterfaz.Componentes.MensajeMed;
import capaNegocio.*;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author JOVF
 */
public class jdGestionarProducto extends javax.swing.JDialog {

    clsMarca objMarca = new clsMarca();
    clsCategoria objCat = new clsCategoria();
    clsProducto objProducto = new clsProducto();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    private int posX = 0, posY = 0;

    /**
     * Creates new form jdPaciente
     */
    public jdGestionarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        getContentPane().setBackground(new Color(0, 0, 0, 0));
        getRootPane().setOpaque(false);
        setBackground(new Color(0, 0, 0, 0));
        cboMarca.setUI(ComboMed.createUI(cboMarca));
        cboCategoria.setUI(ComboMed.createUI(cboCategoria));
        tblDatos.getTableHeader().setDefaultRenderer(new ColorTabla());
        jdcVencimiento.setIcon(new ImageIcon(getClass().getResource("/Iconos/calendario.png")));
        jdcVencimiento.getCalendarButton().setContentAreaFilled(false);
        jdcVencimiento.setBackground(Color.WHITE);
        jdcVencimiento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnBuscar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel2 = new RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        txtCodigo = new capaInterfaz.Componentes.TextoMed();
        txtNombre = new capaInterfaz.Componentes.TextoMed();
        txtPCompra = new capaInterfaz.Componentes.TextoMed();
        txtDescripcion = new capaInterfaz.Componentes.TextoMed();
        txtPVenta = new capaInterfaz.Componentes.TextoMed();
        txtStock = new capaInterfaz.Componentes.TextoMed();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cboMarca = new javax.swing.JComboBox<>();
        chkVigencia = new capaInterfaz.Componentes.CheckMed();
        jdcVencimiento = new com.toedter.calendar.JDateChooser();
        btnSalir2 = new capaInterfaz.Componentes.BotonMedGradiente();
        btnNuevo = new capaInterfaz.Componentes.BotonMedGradiente();
        btnModificar = new capaInterfaz.Componentes.BotonMedGradiente();
        btnDarBaja = new capaInterfaz.Componentes.BotonMedGradiente();
        btnEliminar = new capaInterfaz.Componentes.BotonMedGradiente();
        btnBuscar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel2.setText("Codigo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 16, -1, 30));

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel4.setText("Descripción:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel5.setText("Precio venta:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel10.setText("Precio compra:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel7.setText("Stock:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel6.setText("Vigencia:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel8.setText("F. Vencimiento:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        cboCategoria.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        cboCategoria.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(cboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 232, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDatos.setRowHeight(24);
        tblDatos.setSelectionBackground(new java.awt.Color(16, 171, 131));
        tblDatos.setShowVerticalLines(false);
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 850, 334));

        txtCodigo.setText("");
        txtCodigo.setPlaceholder("");
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 17, 190, -1));

        txtNombre.setText("");
        txtNombre.setPlaceholder("");
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 310, -1));

        txtPCompra.setText("");
        txtPCompra.setPlaceholder("");
        txtPCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPCompraKeyTyped(evt);
            }
        });
        jPanel2.add(txtPCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 106, -1));

        txtDescripcion.setText("");
        txtDescripcion.setPlaceholder("");
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 310, -1));

        txtPVenta.setText("");
        txtPVenta.setPlaceholder("");
        txtPVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPVentaKeyPressed(evt);
            }
        });
        jPanel2.add(txtPVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 110, -1));

        txtStock.setText("");
        txtStock.setPlaceholder("");
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 104, -1));

        jLabel9.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel9.setText("Categoría:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel11.setText("Marca:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        cboMarca.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        cboMarca.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(cboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 232, 30));

        chkVigencia.setText("Vigente");
        jPanel2.add(chkVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));
        jPanel2.add(jdcVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 189, -1));

        btnSalir2.setText("Salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 170, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 170, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 330, 170, -1));

        btnDarBaja.setText("Dar de baja");
        btnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaActionPerformed(evt);
            }
        });
        jPanel2.add(btnDarBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, 170, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 170, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 12, -1, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/baja.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 470, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1150, 650));

        jPanel1.setBackground(new java.awt.Color(16, 171, 131));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIONAR PRODUCTO");

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusable(false);
        btnSalir.setPreferredSize(new java.awt.Dimension(49, 25));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit (2)_1.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(360, 360, 360)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 158));
        jPanel1.setBorder(BorderFactory.createMatteBorder(3, 3, 0, 3, Color.GRAY));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1270, 630));
        jPanel3.setBorder(BorderFactory.createMatteBorder(0, 3, 3, 3, Color.GRAY));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    public void alinearTabla(JTable tabla) {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        TableModel tableModel = tabla.getModel();

        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++) {
            tabla.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_formMouseDragged
    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();//metodo solo para ingresar numeros
        if (c < '0' || c > '9') {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        if (txtCodigo.getText().length() >= 6) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    public void listarMarcas() {
        ResultSet rsMarcas = null;
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        cboMarca.setModel(model);

        try {
            rsMarcas = objMarca.listarMarcasVigentes();
            while (rsMarcas.next()) {
                model.addElement(rsMarcas.getString("nombre"));
            }
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(), 3);

        }

    }

    public void listarCategorias() {
        ResultSet rsCategoria = null;
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        cboCategoria.setModel(model);

        try {
            rsCategoria = objCat.listarCategoriasVigentes();
            while (rsCategoria.next()) {
                model.addElement(rsCategoria.getString("nombre"));
            }
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(), 3);

        }

    }
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
//        char c = evt.getKeyChar();//metodo solo para ingresar letras
//        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c > ' ') && (c < 'á' || c > 'ú') && (c < 'Á' || c > 'Ú')) {
//            evt.consume();
//            Toolkit.getDefaultToolkit().beep();
//
//        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtPCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCompraKeyTyped
        // TODO add your handling code here:
//        char c = evt.getKeyChar();//metodo solo para ingresar numeros
//        if (c < '0' || c > '9') {
//            evt.consume();
//            Toolkit.getDefaultToolkit().beep();
//        }
//        if (txtPCompra.getText().length() >= 8) {
//            evt.consume();
//            Toolkit.getDefaultToolkit().beep();
//        }
    }//GEN-LAST:event_txtPCompraKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        try {
            if (btnNuevo.getText().equals("Nuevo")) {
                btnNuevo.setText("Guardar");
                txtCodigo.setText(String.valueOf(objProducto.generarCodigoProducto()));

            } else {
                btnNuevo.setText("Nuevo");
                //Guardar

                if (validarCampos()) {
                    objProducto.registrarProducto(Integer.parseInt(txtCodigo.getText()),
                            txtNombre.getText().toUpperCase(),
                            txtDescripcion.getText(),
                            Double.parseDouble(txtPVenta.getText()),
                            Double.parseDouble(txtPCompra.getText()),
                            Integer.parseInt(txtStock.getText()),
                            chkVigencia.isSelected(),
                            sdf.format(jdcVencimiento.getDate()),
                            objMarca.obtenerCodigoMarca(cboMarca.getSelectedItem().toString()),
                            objCat.obtenerCodigoCategoria(cboCategoria.getSelectedItem().toString()));
                    new MensajeMed().mostrar(this, "Se registro correctamente el producto", 2);

                }

                listarProductos();
            }

        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(), 3);

        }
    }//GEN-LAST:event_btnNuevoActionPerformed
    public Boolean validarCampos() {
        if (txtNombre.getText().isEmpty() || txtCodigo.getText().isEmpty() || txtDescripcion.getText().isEmpty()
                || txtPCompra.getText().isEmpty() || txtPVenta.getText().isEmpty() || txtStock.getText().isEmpty()) {
            new MensajeMed().mostrar(this, "Por favor complete todos los campos", 0);
            return false;
        }
        return true;
    }

    public void listarProductos() {
        ResultSet rsLista = null;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Descripcion");
        model.addColumn("P. Venta");
        model.addColumn("P. Compra");
        model.addColumn("Stock");
        model.addColumn("Vigencia");
        model.addColumn("F. Vencimiento");
        model.addColumn("Marca");
        model.addColumn("Categoria");
        tblDatos.setModel(model);
        try {
            rsLista = objProducto.listarProductos();
            while (rsLista.next()) {

                model.addRow(new Object[]{
                    rsLista.getInt("codproducto"),
                    rsLista.getString("nombre"),
                    rsLista.getString("descripcion"),
                    rsLista.getDouble("precioventa"),
                    rsLista.getDouble("preciocompra"),
                    rsLista.getInt("stock"),
                    rsLista.getBoolean("vigencia") ? "Vigente" : "No Vigente",
                    rsLista.getDate("fechavencimiento"),
                    rsLista.getString("marca"),
                    rsLista.getString("categoria")
                });

            }
            alinearTabla(tblDatos);
            
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(), 3);

        }
        limpiarControles();
    }

    private void btnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaActionPerformed
        // TODO add your handling code here:

        try {
            if (!txtCodigo.getText().isEmpty()) {
                objProducto.darBajaProducto(Integer.parseInt(txtCodigo.getText()));
                listarProductos();
                new MensajeMed().mostrar(this, "Se dio de baja al producto", 2);

            } else {
                new MensajeMed().mostrar(this, "Por favor ingrese el codigo del producto a dar de baja", 0);
//                JOptionPane.showMessageDialog(this, "Por favor ingrese codigo de product a dar de baja");
            }

        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(), 3);

        }
    }//GEN-LAST:event_btnDarBajaActionPerformed

    private void limpiarControles(){
    txtCodigo.setText("");
    txtNombre.setText("");
    txtDescripcion.setText("");
    txtPVenta.setText("");
    txtPCompra.setText("");
    txtStock.setText("");
  
    
    }
    private void buscarProducto() {
        try {
            if (!txtCodigo.getText().isEmpty()) {
                ResultSet rsProducto = objProducto.buscarProducto(Integer.parseInt(txtCodigo.getText()));
                if (rsProducto.next()) {
                    txtNombre.setText(rsProducto.getString("nombre"));
                    txtDescripcion.setText(rsProducto.getString("descripcion"));
                    txtPVenta.setText(String.valueOf(rsProducto.getDouble("precioventa")));
                    txtPCompra.setText(String.valueOf(rsProducto.getDouble("preciocompra")));
                    txtStock.setText(String.valueOf(rsProducto.getInt("stock")));
                    chkVigencia.setSelected(rsProducto.getBoolean("vigencia"));
                    jdcVencimiento.setDate(rsProducto.getDate("fechavencimiento"));
                    cboCategoria.setSelectedItem(rsProducto.getString("categoria"));
                    cboMarca.setSelectedItem(rsProducto.getString("marca"));

                } else {
                    new MensajeMed().mostrar(this, "No se encuentra registrada el producto buscado", 0);

                }

            } else {
                new MensajeMed().mostrar(this, "Por favor ingrese codigo de categoria a buscar", 0);
            }

        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(), 3);
        }
    }
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
            if (!txtCodigo.getText().isEmpty()) {
                objProducto.modificarProducto(Integer.parseInt(txtCodigo.getText()),
                        txtNombre.getText(),
                        txtDescripcion.getText(),
                        Double.parseDouble(txtPVenta.getText()),
                        Double.parseDouble(txtPCompra.getText()),
                        Integer.parseInt(txtStock.getText()),
                        chkVigencia.isSelected(),
                        sdf.format(jdcVencimiento.getDate()),
                        objMarca.obtenerCodigoMarca(cboMarca.getSelectedItem().toString()),
                        objCat.obtenerCodigoCategoria(cboCategoria.getSelectedItem().toString()));
                new MensajeMed().mostrar(this, "Se modifico el producto", 2);

                listarProductos();

            } else {
                JOptionPane.showMessageDialog(this, "Por favor ingrese codigo de producto a modificar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            if (!txtCodigo.getText().isEmpty()) {
                if (!objProducto.verificarProductoEnVenta(Integer.parseInt(txtCodigo.getText()))) {
                    if (objProducto.verificarStock(Integer.parseInt(txtCodigo.getText()))) {
                        int rpta = new MensajeMed().mostrar(this, "Esta seguro de eliminar el producto", 1);
                        if (rpta == JOptionPane.YES_OPTION) {
                            objProducto.eliminarProducto(Integer.parseInt(txtCodigo.getText()));
                            new MensajeMed().mostrar(this, "Se elimino el producto", 2);
                        }

                        listarProductos();
                    } else {
                        new MensajeMed().mostrar(this, "El producto no puede ser eliminado ya que tiene stock en su haber", 1);
                    }

                } else {
                    new MensajeMed().mostrar(this, "El producto no puede ser eliminado ya que esta presente en ventas", 1);
                }

            } else {
                new MensajeMed().mostrar(this, "Por favor ingrese codigo de producto a eliminar", 0);
            }

        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(), 3);

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        listarMarcas();
        listarCategorias();
        listarProductos();
    }//GEN-LAST:event_formWindowOpened

    private void txtPVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPVentaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPVentaKeyPressed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        // TODO add your handling code here:
        txtCodigo.setText(String.valueOf(tblDatos.getValueAt(tblDatos.getSelectedRow(), 0)));
        buscarProducto();
    }//GEN-LAST:event_tblDatosMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        buscarProducto();

    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
         // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdGestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdGestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdGestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdGestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdGestionarProducto dialog = new jdGestionarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private capaInterfaz.Componentes.BotonMedGradiente btnDarBaja;
    private capaInterfaz.Componentes.BotonMedGradiente btnEliminar;
    private capaInterfaz.Componentes.BotonMedGradiente btnModificar;
    private capaInterfaz.Componentes.BotonMedGradiente btnNuevo;
    private javax.swing.JButton btnSalir;
    private capaInterfaz.Componentes.BotonMedGradiente btnSalir2;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JComboBox<String> cboMarca;
    private capaInterfaz.Componentes.CheckMed chkVigencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcVencimiento;
    private java.awt.Label label1;
    private javax.swing.JTable tblDatos;
    private capaInterfaz.Componentes.TextoMed txtCodigo;
    private capaInterfaz.Componentes.TextoMed txtDescripcion;
    private capaInterfaz.Componentes.TextoMed txtNombre;
    private capaInterfaz.Componentes.TextoMed txtPCompra;
    private capaInterfaz.Componentes.TextoMed txtPVenta;
    private capaInterfaz.Componentes.TextoMed txtStock;
    // End of variables declaration//GEN-END:variables
}
