/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaInterfaz;

import capaInterfaz.Componentes.Mail;
import capaInterfaz.Componentes.MensajeMed;
import capaInterfaz.Componentes.RoundedPanelSinSombra;
import capaNegocio.*;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingWorker;

/**
 *
 * @author CMFerrer
 */
public class jdInicioSesion extends javax.swing.JDialog {

    //Usuario miUsuarioBiblio = new Usuario();
    clsUsuario miUsuario = new clsUsuario();
    static String nomUsuario = "";
    static String usu = "";
    static String preg;

    static ArrayList recuerdame = new ArrayList();
    //String [] recuerdame = new String[2];
    static String[] usuario;

    Preferences preferencia;
    boolean recordarPreferencia;
    static boolean recuperacion;

    /**
     * Creates new form jdInicioSesion
     */
    public jdInicioSesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        imagen(lblImagen, "/Iconos/inicio.png");
        getContentPane().setBackground(new Color(0, 0, 0, 0));
        getRootPane().setOpaque(false);
        setBackground(new Color(0, 0, 0, 0));

        preferencia = Preferences.userNodeForPackage(this.getClass());
        // Put the boolean of the rememberMe preferencia
        recordarPreferencia = preferencia.getBoolean("rememberMe", Boolean.valueOf(""));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new capaInterfaz.Componentes.RoundedPanelSinSombra(300, new Color(51,51,51));
        lblImagen = new javax.swing.JLabel();
        Ventanas = new javax.swing.JPanel();
        InicioSesion = new capaInterfaz.Componentes.RoundedPanelSinSombra(40, Color.WHITE);
        btnIniciarSesion = new capaInterfaz.Componentes.BotonMed();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new capaInterfaz.Componentes.TextoMed();
        txtContrasenia = new capaInterfaz.Componentes.TextoSecretoMed();
        btnSalir = new javax.swing.JButton();
        chkRecuerdame = new capaInterfaz.Componentes.CheckMed();
        CodigoRecuperacion = new capaInterfaz.Componentes.RoundedPanelSinSombra(40, Color.WHITE);
        lblPregunta = new javax.swing.JLabel();
        txtCodigoRecuperacion = new capaInterfaz.Componentes.TextoMed();
        botonMed5 = new capaInterfaz.Componentes.BotonMed();
        jLabel1 = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 80, -1));

        Ventanas.setOpaque(false);
        Ventanas.setLayout(new java.awt.CardLayout());

        InicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        InicioSesion.setOpaque(false);
        InicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        InicioSesion.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 360, 40));

        jCheckBox2.setContentAreaFilled(false);
        jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/hidden.png"))); // NOI18N
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        InicioSesion.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 30, 40));

        jLabel3.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 119, 254));
        jLabel3.setText("¿Olvidaste tu contraseña?");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        InicioSesion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 160, -1));

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel4.setText("Inicia sesión con tu cuenta para continuar...");
        InicioSesion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 340, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel5.setText("¡Bienvenido!");
        InicioSesion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        txtUsuario.setText("Nombre de usuario");
        txtUsuario.setName(""); // NOI18N
        txtUsuario.setPlaceholder("Nombre de usuario");
        InicioSesion.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 340, -1));
        InicioSesion.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 340, -1));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusable(false);
        btnSalir.setOpaque(true);
        btnSalir.setPreferredSize(new java.awt.Dimension(49, 25));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit (2).png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        InicioSesion.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 40, -1));

        chkRecuerdame.setText("Recordar sesión");
        chkRecuerdame.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        chkRecuerdame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRecuerdameActionPerformed(evt);
            }
        });
        InicioSesion.add(chkRecuerdame, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        Ventanas.add(InicioSesion, "inicioSesion");

        CodigoRecuperacion.setBackground(new java.awt.Color(255, 255, 255));
        CodigoRecuperacion.setOpaque(false);
        CodigoRecuperacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPregunta.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        lblPregunta.setText("Contraseña olvidada");
        CodigoRecuperacion.add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtCodigoRecuperacion.setText("Código de recuperación");
        txtCodigoRecuperacion.setPlaceholder("Código de recuperación");
        CodigoRecuperacion.add(txtCodigoRecuperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 367, -1));

        botonMed5.setText("Recuperar cuenta");
        botonMed5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMed5ActionPerformed(evt);
            }
        });
        CodigoRecuperacion.add(botonMed5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 370, 40));

        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 119, 254));
        jLabel1.setText("Tengo una cuenta");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        CodigoRecuperacion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        btnSalir1.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit.png"))); // NOI18N
        btnSalir1.setBorder(null);
        btnSalir1.setContentAreaFilled(false);
        btnSalir1.setFocusable(false);
        btnSalir1.setOpaque(true);
        btnSalir1.setPreferredSize(new java.awt.Dimension(49, 25));
        btnSalir1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit (2).png"))); // NOI18N
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        CodigoRecuperacion.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 40, -1));

        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel2.setText("para restablecer una nueva contraseña");
        CodigoRecuperacion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel6.setText("Por favor ingresa tu código de recuperación");
        CodigoRecuperacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(79, 119, 254));
        jLabel7.setText("Olvidé mi código");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        CodigoRecuperacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        Ventanas.add(CodigoRecuperacion, "codigo");

        getContentPane().add(Ventanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 480, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        try {
            String contra = new String(txtContrasenia.getPassword());
            if (txtUsuario.getText().equals("Nombre de usuario") || contra.equals("Tu contraseña")) {
                new MensajeMed().mostrar(this, "Falta completar algunos campos", 0);

            } else {
                if (miUsuario.validarVigencia(txtUsuario.getText())) {

                    usuario = miUsuario.inicioSesion(txtUsuario.getText(), txtContrasenia.getPassword());

                    if (usuario == null) {
                        new MensajeMed().mostrar(this, "Contraseña incorrecta, intente nuevamente", 3);
                        limpiar();
                    } else {

                        /*if (chkRecuerdame.isSelected()) {
                            recuerdame.add(txtUsuario.getText());
                            recuerdame.add(new String(txtContrasenia.getPassword()));
                        } else {
                            recuerdame.clear();
                        }*/
                        if (chkRecuerdame.isSelected()) {
                            // Insert into the preferencia the name
                            preferencia.put("User", txtUsuario.getText());
                            preferencia.put("Password", txtContrasenia.getText());
                            preferencia.putBoolean("rememberMe", true);
                        } else if (!chkRecuerdame.isSelected()) {
                            // Reset the preferencia
                            preferencia.put("User", "");
                            preferencia.put("Password", "");
                            preferencia.putBoolean("rememberMe", false);
                        }

                        new MensajeMed().mostrar(this, "<html><div><span style='text-align: left;display: block;'>¡Bienvenido</span><br><strong style='text-align: center;display: block;'>" + usuario[3] + "</strong><br><div style='text-align: right;display: block;'>al sistema!</div></div><br></html>", 2);

                        dispose();
                    }
                } else {
                    new MensajeMed().mostrar(this, "Usuario no está activo o no existe", 3);
                    limpiar();
                }
            }

        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(), 3);
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setText("<html><u>¿Olvidaste tu contraseña?</u></html>");
        jLabel3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setText("¿Olvidaste tu contraseña?");
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        try {

            if (txtUsuario.getText().isEmpty() || txtUsuario.getText().equals(txtUsuario.getPlaceholder())) {
                new MensajeMed().mostrar(this, "Ingrese el nombre de usuario", 0);
            } else {
                if (miUsuario.validarVigencia(txtUsuario.getText())) {

                    nomUsuario = txtUsuario.getText();

                    CardLayout card = (CardLayout) Ventanas.getLayout();

                    imagen(lblImagen, "/Iconos/code.png");
                    jPanel2.repaint();
                    //txtCodigoRecuperacion.setText("");
                    //txtCodigoRecuperacion.requestFocus();
                    txtCodigoRecuperacion.setText("Código de recuperación");
                    txtCodigoRecuperacion.setFont(new Font("Gadugi", Font.BOLD | Font.ITALIC, 18));
                    txtCodigoRecuperacion.setForeground(new Color(221, 220, 220));
                    card.show(Ventanas, "codigo");
                } else {
                    new MensajeMed().mostrar(this, "Usuario no existe o no está vigente", 3);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void botonMed5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMed5ActionPerformed
        // TODO add your handling code here:
        try {
            if (miUsuario.validarCodigoRecuperacion(nomUsuario, txtCodigoRecuperacion.getText())) {
                new MensajeMed().mostrar(this, "<html><div style='text-align: center;'>¡Respuesta correcta!<br>Será redirigido a otra ventana para cambiar su contraseña</div></html>", 2);
                this.setVisible(false);
                recuperacion = true;
                jdModificarContrasenia mc = new jdModificarContrasenia(null, true);
                mc.setVisible(true);
                jLabel1MouseClicked(null);
                this.setVisible(true);

            } else {
                new MensajeMed().mostrar(this, "Código incorrecto", 3);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botonMed5ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Ventanas.getLayout();

        imagen(lblImagen, "/Iconos/inicio.png");
        jPanel2.repaint();
        card.show(Ventanas, "inicioSesion");
        limpiar();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setText("<html><u>Tengo una cuenta</u></html>");
        jLabel1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setText("Tengo una cuenta");
    }//GEN-LAST:event_jLabel1MouseExited

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:        
        if (jCheckBox2.isSelected()) {
            jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/hidden.png")));
            txtContrasenia.setEchoChar('•');
        } else {
            jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/view.png")));
            txtContrasenia.setEchoChar((char) 0);
        }

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void chkRecuerdameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRecuerdameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRecuerdameActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        int respuesta = new MensajeMed().mostrar(this, "<html><div style='text-align: center;'>Nuevo código de recuperación<br>Se le enviará un nuevo código ¿Está de acuerdo?</div></html>", 0);
        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                new Mail().enviarNuevoCodigo(nomUsuario);
            } catch (Exception ex) {
                Logger.getLogger(jdInicioSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jLabel7.setText("<html><u>Olvidé mi código</u></html>");
        jLabel7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        jLabel7.setText("Olvidé mi código");
    }//GEN-LAST:event_jLabel7MouseExited

    private void imagen(JLabel lbl, String ruta) {
        ImageIcon imagen = new ImageIcon(getClass().getResource(ruta));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH));

        lbl.setIcon(icono);
        this.repaint();

    }

    private void limpiar() {
        txtContrasenia.setText("Tu contraseña");
        txtContrasenia.setFont(new Font("Gadugi", Font.BOLD | Font.ITALIC, 18));
        txtContrasenia.setForeground(new Color(221, 220, 220));
        txtContrasenia.setEchoChar((char) 0);
        txtUsuario.setText("");
        txtUsuario.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdInicioSesion dialog = new jdInicioSesion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CodigoRecuperacion;
    private javax.swing.JPanel InicioSesion;
    private javax.swing.JPanel Ventanas;
    private capaInterfaz.Componentes.BotonMed botonMed5;
    private capaInterfaz.Componentes.BotonMed btnIniciarSesion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private capaInterfaz.Componentes.CheckMed chkRecuerdame;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPregunta;
    private capaInterfaz.Componentes.TextoMed txtCodigoRecuperacion;
    private capaInterfaz.Componentes.TextoSecretoMed txtContrasenia;
    private capaInterfaz.Componentes.TextoMed txtUsuario;
    // End of variables declaration//GEN-END:variables

}
