/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaInterfaz;

import capaInterfaz.Componentes.ColorTabla;
import capaInterfaz.Componentes.RoundedPanel;
import capaInterfaz.Componentes.ComboMed;
import capaInterfaz.Componentes.MensajeMed;
import capaNegocio.clsProveedor;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author CMFerrer
 */
public class jdManProveedor extends javax.swing.JDialog {
clsProveedor objProv = new clsProveedor();
    private int posX = 0, posY = 0;
    /**
     * Creates new form jdPaciente
     */
    public String ruc;
    public jdManProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        getContentPane().setBackground(new Color(0, 0, 0, 0));
        getRootPane().setOpaque(false);
        setBackground(new Color(0, 0, 0, 0));
        
        cboRubro.setUI(ComboMed.createUI(cboRubro));
        tblDatos.getTableHeader().setDefaultRenderer(new ColorTabla());
        
        btnBus.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
    }
    public void alinearTabla(JTable tabla) {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        TableModel tableModel = tabla.getModel();

        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++) {
            tabla.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNuevo = new capaInterfaz.Componentes.BotonMedGradiente();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboRubro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        txtRuc = new capaInterfaz.Componentes.TextoMed();
        txtRAZ = new capaInterfaz.Componentes.TextoMed();
        txtTel = new capaInterfaz.Componentes.TextoMed();
        txtWeb = new capaInterfaz.Componentes.TextoMed();
        txtCorreo = new capaInterfaz.Componentes.TextoMed();
        txtCiudad = new capaInterfaz.Componentes.TextoMed();
        chkEstado = new capaInterfaz.Componentes.CheckMed();
        btnModificar = new capaInterfaz.Componentes.BotonMedGradiente();
        btnEliminar = new capaInterfaz.Componentes.BotonMedGradiente();
        btnDarBaja = new capaInterfaz.Componentes.BotonMedGradiente();
        btnSalir2 = new capaInterfaz.Componentes.BotonMedGradiente();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnBus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel2.setText("Ruc:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 30));

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setText("Razón Social:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel4.setText("Web:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 170, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel5.setText("Correo:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel10.setText("Teléfono:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 18, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel7.setText("Ciudad:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel6.setText("Rubro:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel8.setText("Estado:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        cboRubro.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        cboRubro.setForeground(new java.awt.Color(51, 51, 51));
        cboRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agrícola", "Veterinario", "Químico" }));
        jPanel2.add(cboRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 200, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDatos.setRowHeight(24);
        tblDatos.setSelectionBackground(new java.awt.Color(16, 171, 131));
        tblDatos.setShowVerticalLines(false);
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 555, 242));

        txtRuc.setForeground(new java.awt.Color(0, 0, 0));
        txtRuc.setText("");
        txtRuc.setPlaceholder("");
        txtRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucActionPerformed(evt);
            }
        });
        txtRuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucKeyTyped(evt);
            }
        });
        jPanel2.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        txtRAZ.setText("");
        txtRAZ.setPlaceholder("");
        txtRAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRAZActionPerformed(evt);
            }
        });
        txtRAZ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRAZKeyTyped(evt);
            }
        });
        jPanel2.add(txtRAZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        txtTel.setText("");
        txtTel.setPlaceholder("");
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });
        jPanel2.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 16, -1, -1));

        txtWeb.setText("");
        txtWeb.setPlaceholder("");
        txtWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWebActionPerformed(evt);
            }
        });
        jPanel2.add(txtWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        txtCorreo.setText("");
        txtCorreo.setPlaceholder("");
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        txtCiudad.setText("");
        txtCiudad.setPlaceholder("");
        jPanel2.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        chkEstado.setSelected(false);
        chkEstado.setText("(Activo)");
        jPanel2.add(chkEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 170, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 170, -1));

        btnDarBaja.setText("Dar de baja");
        btnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaActionPerformed(evt);
            }
        });
        jPanel2.add(btnDarBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 170, -1));

        btnSalir2.setText("Salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 170, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/baja.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        btnBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        btnBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBusMouseClicked(evt);
            }
        });
        jPanel2.add(btnBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 850, 500));

        jPanel1.setBackground(new java.awt.Color(16, 171, 131));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIONAR PROVEEDOR");

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusable(false);
        btnSalir.setPreferredSize(new java.awt.Dimension(49, 25));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit (2)_1.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 158));
        jPanel1.setBorder(BorderFactory.createMatteBorder(3, 3, 0, 3, Color.GRAY));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 960, 550));
        jPanel3.setBorder(BorderFactory.createMatteBorder(0, 3, 3, 3, Color.GRAY));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        posX = evt.getX();
	posY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_formMouseDragged

    private void txtRucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();//metodo solo para ingresar numeros
        if (c < '0' || c > '9') {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        //metodo solo para ingresar numeros
        if ((txtRuc.getText().length() == 11) ) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
    }//GEN-LAST:event_txtRucKeyTyped
public boolean valruc(){
    if((txtRuc.getText().substring(0,1)!="20" ||txtRuc.getText().substring(0,1)!="10") && (txtRuc.getText().length() != 11) ){
        new MensajeMed().mostrar(this, "Ruc no válido, debe empezar por 20 o 10 y tener 11 dígitos.",3);
        txtRuc.requestFocus();
        return false;
    }
    return true;
}
    private void txtRAZKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRAZKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();//metodo solo para ingresar letras
        if((c< 'a' || c>'z') && (c< 'A' || c>'Z')&& (c>' ')&&(c<'á'||c>'ú')&&(c<'Á'||c>'Ú')){
            evt.consume();
          Toolkit.getDefaultToolkit().beep();
    
        }
    }//GEN-LAST:event_txtRAZKeyTyped

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();//metodo solo para ingresar numeros
        if (c < '0' || c > '9') {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
        if (txtTel.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtTelKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
private void buscarPro(){
               ResultSet rsPr = null;
           String rubro="";
        try {
            if(txtRuc.getText().isEmpty()){
                 new MensajeMed().mostrar(this, "Ingrese ruc a buscar...",0);
                txtRuc.requestFocus();
            }else{
                rsPr=objProv.buscarProv(txtRuc.getText());
                if(rsPr.next()){
                    txtRAZ.setText(rsPr.getString("razonsocial"));
                    txtCorreo.setText(rsPr.getString("correo"));
                    txtTel.setText(String.valueOf(rsPr.getString("telefono")));
                    txtWeb.setText(String.valueOf(rsPr.getString("web")));
                    txtCiudad.setText(String.valueOf(rsPr.getString("ciudad")));
                    rubro=rsPr.getString("rubro");
                    if(rubro.equals("A")) cboRubro.setSelectedItem("Agrícola");
                    if(rubro.equals("V")) cboRubro.setSelectedItem("Veterinario");
                    if(rubro.equals("Q")) cboRubro.setSelectedItem("Químico");
                  
                    chkEstado.setSelected(rsPr.getBoolean("estado"));
                }else{
                    new MensajeMed().mostrar(this, "Ruc no registrado...",0);
                    
                }
            }
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }
    }
    private void txtWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWebActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
         String rubro="";
    
        try {
            if(txtRuc.getText().isEmpty() || txtRAZ.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtTel.getText().isEmpty() || txtCiudad.getText().isEmpty()){
                new MensajeMed().mostrar(this, "Complete todos los campos",0);
            } else {
                if (valruc()){
                   if (objProv.validar(txtRuc.getText())){
                    if (cboRubro.getSelectedItem().equals("Agrícola")) rubro="A";
                    if (cboRubro.getSelectedItem().equals("Veterinario")) rubro="V";
                    if (cboRubro.getSelectedItem().equals("Químico")) rubro="Q";
                    
                    objProv.registrarProv(txtRuc.getText(),txtRAZ.getText(), txtCorreo.getText(), txtWeb.getText(), txtTel.getText(), txtCiudad.getText(), rubro, chkEstado.isSelected());
                  new MensajeMed().mostrar(this, "Se registró correctamente.", 2);
                  listarProveedores();
                  limpiar();
                }else{
                     new MensajeMed().mostrar(this, "Ruc ya está registrado!",3);

                } 
                }
                
            }
              
            
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaActionPerformed
        // TODO add your handling code here:
         try {
            if(txtRuc.getText().isEmpty()){
                new MensajeMed().mostrar(this, "Ingrese ruc a dar de baja...",0);
            }else{
                objProv.darBajaHab(txtRuc.getText());
                new MensajeMed().mostrar(this, "Se dio de baja correctamente.", 2);
                listarProveedores();
                limpiar();
            }
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }
    }//GEN-LAST:event_btnDarBajaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
         try {
            if(txtRuc.getText().isEmpty()){
                new MensajeMed().mostrar(this, "Ingrese ruc a dar de baja...",0);
            }else{
                String rubro=" ";
              
                    if (cboRubro.getSelectedItem().equals("Agrícola")) rubro="A";
                    if (cboRubro.getSelectedItem().equals("Veterinario")) rubro="V";
                    if (cboRubro.getSelectedItem().equals("Químico")) rubro="Q";
                objProv.modificarProv(txtRuc.getText(),txtRAZ.getText(), txtCorreo.getText(), txtWeb.getText(), txtTel.getText(), txtCiudad.getText(), rubro, chkEstado.isSelected());
                new MensajeMed().mostrar(this, "Se modificó correctamente", 2);
                listarProveedores();
                limpiar();
                 
            }
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
          try {
            if(txtRuc.getText().isEmpty()){
                new MensajeMed().mostrar(this, "Ingrese ruc a eliminar...",0);
            }else{
                if(objProv.verfificarPro(txtRuc.getText())){
                    int rpta = new MensajeMed().mostrar(this, "Está seguro de eliminar proveedor?", 1);
                    if (rpta == JOptionPane.YES_OPTION) {
                objProv.eliminarProv(txtRuc.getText());
                new MensajeMed().mostrar(this, "Se eliminó correctamente", 2);
                limpiar();
                    }
                listarProveedores();
                }else{
                    new MensajeMed().mostrar(this, "No se puede eliminar este proveedor porque tiene compras asignadas.",3);
                }
            }
        } catch (Exception e) {
            new MensajeMed().mostrar(this, e.getMessage(),3);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        // TODO add your handling code here:
        txtRuc.setText(String.valueOf(tblDatos.getValueAt(tblDatos.getSelectedRow(),0)));
        buscarPro();
    }//GEN-LAST:event_tblDatosMouseClicked

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        listarProveedores();
        txtRuc.setText(ruc);
    }//GEN-LAST:event_formWindowOpened

    private void txtRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucActionPerformed

    private void txtRAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRAZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRAZActionPerformed


    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void btnBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusMouseClicked
         // TODO add your handling code here:
         buscarPro();
    }//GEN-LAST:event_btnBusMouseClicked
 private void limpiar(){
     txtCiudad.setText("");
     txtCorreo.setText("");
     txtWeb.setText("");
     txtTel.setText("");
     txtRAZ.setText("");
     txtRuc.setText("");
     chkEstado.setEnabled(false);
     cboRubro.setSelectedIndex(0);
 }
    private void listarProveedores(){
        ResultSet rsPr =null;
        String rubro="";
        DefaultTableModel modeloPr=new DefaultTableModel();
        modeloPr.addColumn("Ruc");
        modeloPr.addColumn("Razon Social");
        modeloPr.addColumn("Correo");
        modeloPr.addColumn("Web");
        modeloPr.addColumn("Tel.");
        modeloPr.addColumn("Ciudad");
        modeloPr.addColumn("Rubro");
        modeloPr.addColumn("Estado");
        tblDatos.setModel(modeloPr);
        try {
            rsPr=objProv.listarProveedores();
            while(rsPr.next()){
                rubro=rsPr.getString("rubro");
                    if(rubro.equals("A")) rubro=("Agrícola");
                    if(rubro.equals("V")) rubro=("Veterinario");
                    if(rubro.equals("Q")) rubro=("Químico");
                modeloPr.addRow(new Object[]{
                    rsPr.getString("ruc"),
                    rsPr.getString("razonsocial"),
                    rsPr.getString("correo"),
                    rsPr.getString("web"),
                    rsPr.getString("telefono"),
                    rsPr.getString("ciudad"),
                    rubro,
                    rsPr.getBoolean("estado")? "Activo" : "Inactivo",});
            }
            alinearTabla(tblDatos);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdManProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdManProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdManProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdManProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdManProveedor dialog = new jdManProveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBus;
    private capaInterfaz.Componentes.BotonMedGradiente btnDarBaja;
    private capaInterfaz.Componentes.BotonMedGradiente btnEliminar;
    private capaInterfaz.Componentes.BotonMedGradiente btnModificar;
    private capaInterfaz.Componentes.BotonMedGradiente btnNuevo;
    private javax.swing.JButton btnSalir;
    private capaInterfaz.Componentes.BotonMedGradiente btnSalir2;
    private javax.swing.JComboBox<String> cboRubro;
    private capaInterfaz.Componentes.CheckMed chkEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private capaInterfaz.Componentes.TextoMed txtCiudad;
    private capaInterfaz.Componentes.TextoMed txtCorreo;
    private capaInterfaz.Componentes.TextoMed txtRAZ;
    private capaInterfaz.Componentes.TextoMed txtRuc;
    private capaInterfaz.Componentes.TextoMed txtTel;
    private capaInterfaz.Componentes.TextoMed txtWeb;
    // End of variables declaration//GEN-END:variables
}
