/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaInterfaz.Componentes;

import capaNegocio.clsUsuario;
import jakarta.activation.DataHandler;
import jakarta.activation.DataSource;
import jakarta.activation.FileDataSource;
import jakarta.mail.BodyPart;
import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.PasswordAuthentication;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeBodyPart;
import jakarta.mail.internet.MimeMessage;
import jakarta.mail.internet.MimeMultipart;
import java.sql.ResultSet;

import java.util.Properties;

/**
 *
 * @author CMFerrer
 */
public class Mail {

    private final Properties props;

    public Mail() {
        props = new Properties();

        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        props.put("from", "bioquimicanorteandino@gmail.com");
        props.put("username", "bioquimicanorteandino@gmail.com");
        props.put("password", "bioquimicadae");
    }

    public void enviar(String to, String subject, String content) throws MessagingException {
        Session sesion = Session.getInstance(props, new jakarta.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(props.getProperty("username"), props.getProperty("password"));
            }
        });

        Message mensaje = new MimeMessage(sesion);
        mensaje.setFrom(new InternetAddress(props.getProperty("from")));
        mensaje.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
        mensaje.setSubject(subject);

        MimeMultipart multipart = new MimeMultipart("related");

        BodyPart messageBodyPart = new MimeBodyPart();
        messageBodyPart.setContent(content, "text/html");
        multipart.addBodyPart(messageBodyPart);

        messageBodyPart = new MimeBodyPart();
        DataSource fds = new FileDataSource("src/Iconos/logo.png");

        messageBodyPart.setDataHandler(new DataHandler(fds));
        messageBodyPart.setHeader("Content-ID", "<image>");
        multipart.addBodyPart(messageBodyPart);

        mensaje.setContent(multipart);

        Transport.send(mensaje);

    }

    public void enviarNuevoCodigo(String usuario) throws MessagingException, Exception {
        clsUsuario miUsuario = new clsUsuario();

        String codRecuperacion = miUsuario.generarCodigoRecuperacion(16);
        ResultSet rsUsuario = miUsuario.actualizarCodigoRecuperacion(usuario, codRecuperacion);

        String to = null;
        String subject = null;
        String content = null;
        if (rsUsuario.next()) {
            to = rsUsuario.getString("correo");
            subject = "Código de recuperación";
            /*content = "<div style=\"background-color: #090446; padding: 16px; margin-bottom: 10px;\"><h1 style=\"text-align: center; font-family: 'Verdana';\"><span style=\"color: #ffffff;\"><strong>Bioquimica del Norte Andino</strong></span></h1></div><div style=\"font-family: 'Verdana'; background-color: #0904450d; padding: 16px; padding-left: 36px;\"><p>Hola " + rsUsuario.getString("nombres") + " " + rsUsuario.getString("apellidos") + ":</p><p>&nbsp;</p><p>Este es tu nuevo <strong>c&oacute;digo de recuperaci&oacute;n</strong>:</p><p style=\"text-align: center;\"><strong>" + codRecuperacion + "</strong></p><p style=\"text-align: center;\">&nbsp;</p><p style=\"text-align: center;\">Atentamente</p><p style=\"text-align: center;\"><img src=\"cid:image\" alt=\"logo\" /></p></div></div>";*/
            content = "<!DOCTYPE html>\n"
                    + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"\n"
                    + "    style=\"width:100%;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0\">\n"
                    + "\n"
                    + "<head>\n"
                    + "    <meta charset=\"UTF-8\">\n"
                    + "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\n"
                    + "    <meta name=\"x-apple-disable-message-reformatting\">\n"
                    + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                    + "    <meta content=\"telephone=no\" name=\"format-detection\">\n"
                    + "    <title>Nuevo mensaje</title>\n"
                    + "    <link href=\"https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i\" rel=\"stylesheet\">\n"
                    + "    <style type=\"text/css\">\n"
                    + "        #outlook a {\n"
                    + "            padding: 0;\n"
                    + "        }\n"
                    + "\n"
                    + "        .ExternalClass {\n"
                    + "            width: 100%;\n"
                    + "        }\n"
                    + "\n"
                    + "        .ExternalClass,\n"
                    + "        .ExternalClass p,\n"
                    + "        .ExternalClass span,\n"
                    + "        .ExternalClass font,\n"
                    + "        .ExternalClass td,\n"
                    + "        .ExternalClass div {\n"
                    + "            line-height: 100%;\n"
                    + "        }\n"
                    + "\n"
                    + "        .es-button {\n"
                    + "            mso-style-priority: 100 !important;\n"
                    + "            text-decoration: none !important;\n"
                    + "        }\n"
                    + "\n"
                    + "        a[x-apple-data-detectors] {\n"
                    + "            color: inherit !important;\n"
                    + "            text-decoration: none !important;\n"
                    + "            font-size: inherit !important;\n"
                    + "            font-family: inherit !important;\n"
                    + "            font-weight: inherit !important;\n"
                    + "            line-height: inherit !important;\n"
                    + "        }\n"
                    + "\n"
                    + "        .es-desk-hidden {\n"
                    + "            display: none;\n"
                    + "            float: left;\n"
                    + "            overflow: hidden;\n"
                    + "            width: 0;\n"
                    + "            max-height: 0;\n"
                    + "            line-height: 0;\n"
                    + "            mso-hide: all;\n"
                    + "        }\n"
                    + "\n"
                    + "        [data-ogsb] .es-button {\n"
                    + "            border-width: 0 !important;\n"
                    + "            padding: 15px 25px 15px 25px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "        @media only screen and (max-width:600px) {\n"
                    + "\n"
                    + "            p,\n"
                    + "            ul li,\n"
                    + "            ol li,\n"
                    + "            a {\n"
                    + "                line-height: 150% !important\n"
                    + "            }\n"
                    + "\n"
                    + "            h1,\n"
                    + "            h2,\n"
                    + "            h3,\n"
                    + "            h1 a,\n"
                    + "            h2 a,\n"
                    + "            h3 a {\n"
                    + "                line-height: 120% !important\n"
                    + "            }\n"
                    + "\n"
                    + "            h1 {\n"
                    + "                font-size: 30px !important;\n"
                    + "                text-align: center\n"
                    + "            }\n"
                    + "\n"
                    + "            h2 {\n"
                    + "                font-size: 26px !important;\n"
                    + "                text-align: center\n"
                    + "            }\n"
                    + "\n"
                    + "            h3 {\n"
                    + "                font-size: 20px !important;\n"
                    + "                text-align: center\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-header-body h1 a,\n"
                    + "            .es-content-body h1 a,\n"
                    + "            .es-footer-body h1 a {\n"
                    + "                font-size: 30px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-header-body h2 a,\n"
                    + "            .es-content-body h2 a,\n"
                    + "            .es-footer-body h2 a {\n"
                    + "                font-size: 26px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-header-body h3 a,\n"
                    + "            .es-content-body h3 a,\n"
                    + "            .es-footer-body h3 a {\n"
                    + "                font-size: 20px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-menu td a {\n"
                    + "                font-size: 16px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-header-body p,\n"
                    + "            .es-header-body ul li,\n"
                    + "            .es-header-body ol li,\n"
                    + "            .es-header-body a {\n"
                    + "                font-size: 16px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-content-body p,\n"
                    + "            .es-content-body ul li,\n"
                    + "            .es-content-body ol li,\n"
                    + "            .es-content-body a {\n"
                    + "                font-size: 16px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-footer-body p,\n"
                    + "            .es-footer-body ul li,\n"
                    + "            .es-footer-body ol li,\n"
                    + "            .es-footer-body a {\n"
                    + "                font-size: 16px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-infoblock p,\n"
                    + "            .es-infoblock ul li,\n"
                    + "            .es-infoblock ol li,\n"
                    + "            .es-infoblock a {\n"
                    + "                font-size: 12px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            *[class=\"gmail-fix\"] {\n"
                    + "                display: none !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-m-txt-c,\n"
                    + "            .es-m-txt-c h1,\n"
                    + "            .es-m-txt-c h2,\n"
                    + "            .es-m-txt-c h3 {\n"
                    + "                text-align: center !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-m-txt-r,\n"
                    + "            .es-m-txt-r h1,\n"
                    + "            .es-m-txt-r h2,\n"
                    + "            .es-m-txt-r h3 {\n"
                    + "                text-align: right !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-m-txt-l,\n"
                    + "            .es-m-txt-l h1,\n"
                    + "            .es-m-txt-l h2,\n"
                    + "            .es-m-txt-l h3 {\n"
                    + "                text-align: left !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-m-txt-r img,\n"
                    + "            .es-m-txt-c img,\n"
                    + "            .es-m-txt-l img {\n"
                    + "                display: inline !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-button-border {\n"
                    + "                display: block !important\n"
                    + "            }\n"
                    + "\n"
                    + "            a.es-button,\n"
                    + "            button.es-button {\n"
                    + "                font-size: 20px !important;\n"
                    + "                display: block !important;\n"
                    + "                border-width: 15px 25px 15px 25px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-btn-fw {\n"
                    + "                border-width: 10px 0px !important;\n"
                    + "                text-align: center !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-adaptive table,\n"
                    + "            .es-btn-fw,\n"
                    + "            .es-btn-fw-brdr,\n"
                    + "            .es-left,\n"
                    + "            .es-right {\n"
                    + "                width: 100% !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-content table,\n"
                    + "            .es-header table,\n"
                    + "            .es-footer table,\n"
                    + "            .es-content,\n"
                    + "            .es-footer,\n"
                    + "            .es-header {\n"
                    + "                width: 100% !important;\n"
                    + "                max-width: 600px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-adapt-td {\n"
                    + "                display: block !important;\n"
                    + "                width: 100% !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .adapt-img {\n"
                    + "                width: 100% !important;\n"
                    + "                height: auto !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-m-p0 {\n"
                    + "                padding: 0px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-m-p0r {\n"
                    + "                padding-right: 0px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-m-p0l {\n"
                    + "                padding-left: 0px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-m-p0t {\n"
                    + "                padding-top: 0px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-m-p0b {\n"
                    + "                padding-bottom: 0 !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-m-p20b {\n"
                    + "                padding-bottom: 20px !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-mobile-hidden,\n"
                    + "            .es-hidden {\n"
                    + "                display: none !important\n"
                    + "            }\n"
                    + "\n"
                    + "            tr.es-desk-hidden,\n"
                    + "            td.es-desk-hidden,\n"
                    + "            table.es-desk-hidden {\n"
                    + "                width: auto !important;\n"
                    + "                overflow: visible !important;\n"
                    + "                float: none !important;\n"
                    + "                max-height: inherit !important;\n"
                    + "                line-height: inherit !important\n"
                    + "            }\n"
                    + "\n"
                    + "            tr.es-desk-hidden {\n"
                    + "                display: table-row !important\n"
                    + "            }\n"
                    + "\n"
                    + "            table.es-desk-hidden {\n"
                    + "                display: table !important\n"
                    + "            }\n"
                    + "\n"
                    + "            td.es-desk-menu-hidden {\n"
                    + "                display: table-cell !important\n"
                    + "            }\n"
                    + "\n"
                    + "            .es-menu td {\n"
                    + "                width: 1% !important\n"
                    + "            }\n"
                    + "\n"
                    + "            table.es-table-not-adapt,\n"
                    + "            .esd-block-html table {\n"
                    + "                width: auto !important\n"
                    + "            }\n"
                    + "\n"
                    + "            table.es-social {\n"
                    + "                display: inline-block !important\n"
                    + "            }\n"
                    + "\n"
                    + "            table.es-social td {\n"
                    + "                display: inline-block !important\n"
                    + "            }\n"
                    + "        }\n"
                    + "    </style>\n"
                    + "</head>\n"
                    + "\n"
                    + "<body\n"
                    + "    style=\"width:100%;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0\">\n"
                    + "    <div class=\"es-wrapper-color\" style=\"background-color:#F4F4F4\">\n"
                    + "        <!--[if gte mso 9]><v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\"> <v:fill type=\"tile\" color=\"#f4f4f4\"></v:fill> </v:background><![endif]-->\n"
                    + "        <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top\">\n"
                    + "            <tr class=\"gmail-fix\" height=\"0\" style=\"border-collapse:collapse\">\n"
                    + "                <td style=\"padding:0;Margin:0\">\n"
                    + "                    <table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" align=\"center\"\n"
                    + "                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:600px\">\n"
                    + "                        <tr style=\"border-collapse:collapse\">\n"
                    + "                            <td cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\n"
                    + "                                style=\"padding:0;Margin:0;line-height:1px;min-width:600px\" height=\"0\"><img\n"
                    + "                                    src=\"images/41521605538834349.png\"\n"
                    + "                                    style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;max-height:0px;min-height:0px;min-width:600px;width:600px\"\n"
                    + "                                    alt width=\"600\" height=\"1\"></td>\n"
                    + "                        </tr>\n"
                    + "                    </table>\n"
                    + "                </td>\n"
                    + "            </tr>\n"
                    + "            <tr style=\"border-collapse:collapse\">\n"
                    + "                <td valign=\"top\" style=\"padding:0;Margin:0\">\n"
                    + "                    <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\"\n"
                    + "                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\n"
                    + "                        <tr style=\"border-collapse:collapse\">\n"
                    + "                            <td align=\"center\" style=\"padding:0;Margin:0\">\n"
                    + "                                <table class=\"es-content-body\"\n"
                    + "                                    style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px\"\n"
                    + "                                    cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                    + "                                    <tr style=\"border-collapse:collapse\">\n"
                    + "                                        <td align=\"left\"\n"
                    + "                                            style=\"Margin:0;padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:15px\">\n"
                    + "                                            <!--[if mso]><table style=\"width:580px\" cellpadding=\"0\" cellspacing=\"0\"><tr><td style=\"width:282px\" valign=\"top\"><![endif]-->\n"
                    + "                                            <table class=\"es-left\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\"\n"
                    + "                                                style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left\">\n"
                    + "                                                <tr style=\"border-collapse:collapse\">\n"
                    + "                                                    <td align=\"left\" style=\"padding:0;Margin:0;width:282px\">\n"
                    + "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                            role=\"presentation\"\n"
                    + "                                                            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td class=\"es-infoblock es-m-txt-c\" align=\"left\"\n"
                    + "                                                                    style=\"padding:0;Margin:0;line-height:14px;font-size:12px;color:#CCCCCC\">\n"
                    + "                                                                    <p\n"
                    + "                                                                        style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica\\ neue', helvetica, sans-serif;line-height:14px;color:#CCCCCC;font-size:12px\">\n"
                    + "                                                                        Put your preheader text here<br></p>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </table>\n"
                    + "                                                    </td>\n"
                    + "                                                </tr>\n"
                    + "                                            </table>\n"
                    + "\n"
                    + "                                            <table class=\"es-right\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\"\n"
                    + "                                                style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right\">\n"
                    + "                                                <tr style=\"border-collapse:collapse\">\n"
                    + "                                                    <td align=\"left\" style=\"padding:0;Margin:0;width:278px\">\n"
                    + "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                            role=\"presentation\"\n"
                    + "                                                            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td align=\"right\" class=\"es-infoblock es-m-txt-c\"\n"
                    + "                                                                    style=\"padding:0;Margin:0;line-height:14px;font-size:12px;color:#CCCCCC\">\n"
                    + "                                                                    <p\n"
                    + "                                                                        style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;line-height:14px;color:#CCCCCC;font-size:12px\">\n"
                    + "                                                                        <a href=\"https://viewstripo.email\" class=\"view\"\n"
                    + "                                                                            target=\"_blank\"\n"
                    + "                                                                            style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px;font-family:arial, 'helvetica neue', helvetica, sans-serif\">View\n"
                    + "                                                                            in browser</a></p>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </table>\n"
                    + "                                                    </td>\n"
                    + "                                                </tr>\n"
                    + "                                            </table>\n"
                    + "                                            <!--[if mso]></td></tr></table><![endif]-->\n"
                    + "                                        </td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                            </td>\n"
                    + "                        </tr>\n"
                    + "                    </table>\n"
                    + "                    <table class=\"es-header\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\n"
                    + "                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:#FFA73B;background-repeat:repeat;background-position:center top\">\n"
                    + "                        <tr style=\"border-collapse:collapse\">\n"
                    + "                            <td align=\"center\" bgcolor=\"#10ab83\" style=\"padding:0;Margin:0;background-color:#10ab83\">\n"
                    + "                                <table class=\"es-header-body\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\n"
                    + "                                    style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px\">\n"
                    + "                                    <tr style=\"border-collapse:collapse\">\n"
                    + "                                        <td align=\"left\"\n"
                    + "                                            style=\"Margin:0;padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:20px\">\n"
                    + "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                <tr style=\"border-collapse:collapse\">\n"
                    + "                                                    <td valign=\"top\" align=\"center\"\n"
                    + "                                                        style=\"padding:0;Margin:0;width:580px\">\n"
                    + "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                            role=\"presentation\"\n"
                    + "                                                            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td align=\"center\"\n"
                    + "                                                                    style=\"Margin:0;padding-left:10px;padding-right:10px;padding-top:25px;padding-bottom:25px;font-size:0px\">\n"
                    + "                                                                    <img src=\"cid:image\" alt\n"
                    + "                                                                        style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\"\n"
                    + "                                                                        width=\"170\" height=\"166\"></td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </table>\n"
                    + "                                                    </td>\n"
                    + "                                                </tr>\n"
                    + "                                            </table>\n"
                    + "                                        </td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                            </td>\n"
                    + "                        </tr>\n"
                    + "                    </table>\n"
                    + "                    <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\n"
                    + "                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\n"
                    + "                        <tr style=\"border-collapse:collapse\">\n"
                    + "                            <td style=\"padding:0;Margin:0;background-color:#10ab83\" bgcolor=\"#10ab83\" align=\"center\">\n"
                    + "                                <table class=\"es-content-body\"\n"
                    + "                                    style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px\"\n"
                    + "                                    cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                    + "                                    <tr style=\"border-collapse:collapse\">\n"
                    + "                                        <td align=\"left\" style=\"padding:0;Margin:0\">\n"
                    + "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                <tr style=\"border-collapse:collapse\">\n"
                    + "                                                    <td valign=\"top\" align=\"center\"\n"
                    + "                                                        style=\"padding:0;Margin:0;width:600px\">\n"
                    + "                                                        <table\n"
                    + "                                                            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;background-color:#ffffff;border-radius:4px\"\n"
                    + "                                                            width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                            bgcolor=\"#ffffff\" role=\"presentation\">\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td align=\"center\"\n"
                    + "                                                                    style=\"Margin:0;padding-bottom:5px;padding-left:30px;padding-right:30px;padding-top:35px\">\n"
                    + "                                                                    <h1\n"
                    + "                                                                        style=\"Margin:0;line-height:48px;mso-line-height-rule:exactly;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;font-size:40px;font-style:normal;font-weight:normal;color:#111111\">\n"
                    + "                                                                        <strong>Recuperaci&oacute;n de contrase&ntilde;a</strong></h1>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td bgcolor=\"#ffffff\" align=\"center\"\n"
                    + "                                                                    style=\"Margin:0;padding-top:5px;padding-bottom:5px;padding-left:20px;padding-right:20px;font-size:0\">\n"
                    + "                                                                    <table width=\"100%\" height=\"100%\" cellspacing=\"0\"\n"
                    + "                                                                        cellpadding=\"0\" border=\"0\" role=\"presentation\"\n"
                    + "                                                                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                                        <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                            <td\n"
                    + "                                                                                style=\"padding:0;Margin:0;border-bottom:1px solid #ffffff;background:#FFFFFF none repeat scroll 0% 0%;height:1px;width:100%;margin:0px\">\n"
                    + "                                                                            </td>\n"
                    + "                                                                        </tr>\n"
                    + "                                                                    </table>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </table>\n"
                    + "                                                    </td>\n"
                    + "                                                </tr>\n"
                    + "                                            </table>\n"
                    + "                                        </td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                            </td>\n"
                    + "                        </tr>\n"
                    + "                    </table>\n"
                    + "                    <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\n"
                    + "                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\n"
                    + "                        <tr style=\"border-collapse:collapse\">\n"
                    + "                            <td align=\"center\" style=\"padding:0;Margin:0\">\n"
                    + "                                <table class=\"es-content-body\"\n"
                    + "                                    style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px\"\n"
                    + "                                    cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                    + "                                    <tr style=\"border-collapse:collapse\">\n"
                    + "                                        <td align=\"left\" style=\"padding:0;Margin:0\">\n"
                    + "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                <tr style=\"border-collapse:collapse\">\n"
                    + "                                                    <td valign=\"top\" align=\"center\"\n"
                    + "                                                        style=\"padding:0;Margin:0;width:600px\">\n"
                    + "                                                        <table\n"
                    + "                                                            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;border-radius:4px;background-color:#ffffff\"\n"
                    + "                                                            width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                            bgcolor=\"#ffffff\" role=\"presentation\">\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td class=\"es-m-txt-l\" bgcolor=\"#ffffff\" align=\"left\"\n"
                    + "                                                                    style=\"Margin:0;padding-top:20px;padding-bottom:20px;padding-left:30px;padding-right:30px\">\n"
                    + "                                                                    <p\n"
                    + "                                                                        style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;line-height:27px;color:#666666;font-size:18px\">\n"
                    + "                                                                        Hola xxxxxxxxxx.<br>Estas recibiendo este correo\n"
                    + "                                                                        electr&oacute;nico porque has olvidado tu contrase&oacute;a de\n"
                    + "                                                                        su cuenta.</p>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td class=\"es-m-txt-l\" align=\"left\"\n"
                    + "                                                                    style=\"padding:0;Margin:0;padding-top:20px;padding-left:30px;padding-right:30px\">\n"
                    + "                                                                    <p\n"
                    + "                                                                        style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;line-height:27px;color:#666666;font-size:18px\">\n"
                    + "                                                                        Copie y pegue el siguiente c&oacute;digo en su\n"
                    + "                                                                        aplicaci&oacute;n:</p>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td class=\"es-m-txt-l\" align=\"left\"\n"
                    + "                                                                    style=\"padding:0;Margin:0;padding-top:20px;padding-left:30px;padding-right:30px\">\n"
                    + "                                                                    <a target=\"_blank\" href=\"https://viewstripo.email/\"\n"
                    + "                                                                        style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#10ab83;font-size:18px\">XXX.XXXXXXX.XXX\n"
                    + "                                                                        / XXXXXXXXXXXXX</a></td>\n"
                    + "                                                            </tr>\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td class=\"es-m-txt-l\" align=\"left\"\n"
                    + "                                                                    style=\"padding:0;Margin:0;padding-top:20px;padding-left:30px;padding-right:30px\">\n"
                    + "                                                                    <p\n"
                    + "                                                                        style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;line-height:27px;color:#666666;font-size:18px\">\n"
                    + "                                                                        Si tiene alguna pregunta, solo responda a este\n"
                    + "                                                                        correo electr&oacute;nico; siempre estaremos encantados\n"
                    + "                                                                        de ayudarle.</p>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td class=\"es-m-txt-l\" align=\"left\"\n"
                    + "                                                                    style=\"Margin:0;padding-top:20px;padding-left:30px;padding-right:30px;padding-bottom:40px\">\n"
                    + "                                                                    <p\n"
                    + "                                                                        style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;line-height:27px;color:#666666;font-size:18px\">\n"
                    + "                                                                        Les saluda<br>El equipo de Bioqu&iacute;mica del Norte\n"
                    + "                                                                        Andino</p>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </table>\n"
                    + "                                                    </td>\n"
                    + "                                                </tr>\n"
                    + "                                            </table>\n"
                    + "                                        </td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                            </td>\n"
                    + "                        </tr>\n"
                    + "                    </table>\n"
                    + "                    <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\n"
                    + "                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\n"
                    + "                        <tr style=\"border-collapse:collapse\">\n"
                    + "                            <td align=\"center\" style=\"padding:0;Margin:0\">\n"
                    + "                                <table class=\"es-content-body\"\n"
                    + "                                    style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px\"\n"
                    + "                                    cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                    + "                                    <tr style=\"border-collapse:collapse\">\n"
                    + "                                        <td align=\"left\" style=\"padding:0;Margin:0\">\n"
                    + "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                <tr style=\"border-collapse:collapse\">\n"
                    + "                                                    <td valign=\"top\" align=\"center\"\n"
                    + "                                                        style=\"padding:0;Margin:0;width:600px\">\n"
                    + "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                            role=\"presentation\"\n"
                    + "                                                            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td align=\"center\"\n"
                    + "                                                                    style=\"Margin:0;padding-top:10px;padding-bottom:20px;padding-left:20px;padding-right:20px;font-size:0\">\n"
                    + "                                                                    <table width=\"100%\" height=\"100%\" cellspacing=\"0\"\n"
                    + "                                                                        cellpadding=\"0\" border=\"0\" role=\"presentation\"\n"
                    + "                                                                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                                        <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                            <td\n"
                    + "                                                                                style=\"padding:0;Margin:0;border-bottom:1px solid #f4f4f4;background:#FFFFFF none repeat scroll 0% 0%;height:1px;width:100%;margin:0px\">\n"
                    + "                                                                            </td>\n"
                    + "                                                                        </tr>\n"
                    + "                                                                    </table>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </table>\n"
                    + "                                                    </td>\n"
                    + "                                                </tr>\n"
                    + "                                            </table>\n"
                    + "                                        </td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                            </td>\n"
                    + "                        </tr>\n"
                    + "                    </table>\n"
                    + "                    <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\n"
                    + "                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\n"
                    + "                        <tr style=\"border-collapse:collapse\">\n"
                    + "                            <td align=\"center\" style=\"padding:0;Margin:0\">\n"
                    + "                                <table class=\"es-content-body\"\n"
                    + "                                    style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px\"\n"
                    + "                                    cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                    + "                                    <tr style=\"border-collapse:collapse\">\n"
                    + "                                        <td align=\"left\" style=\"padding:0;Margin:0\">\n"
                    + "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                <tr style=\"border-collapse:collapse\">\n"
                    + "                                                    <td valign=\"top\" align=\"center\"\n"
                    + "                                                        style=\"padding:0;Margin:0;width:600px\">\n"
                    + "                                                        <table\n"
                    + "                                                            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;background-color:#ffecd1;border-radius:4px\"\n"
                    + "                                                            width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                            bgcolor=\"#ffecd1\" role=\"presentation\">\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td align=\"center\" bgcolor=\"#10ab83\"\n"
                    + "                                                                    style=\"padding:0;Margin:0;padding-top:30px;padding-left:30px;padding-right:30px\">\n"
                    + "                                                                    <h3\n"
                    + "                                                                        style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;font-size:20px;font-style:normal;font-weight:normal;color:#111111\">\n"
                    + "                                                                        Necesitas m&aacute;s ayuda?</h3>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td esdev-links-color=\"#ffa73b\" align=\"center\"\n"
                    + "                                                                    bgcolor=\"#10ab83\"\n"
                    + "                                                                    style=\"padding:0;Margin:0;padding-bottom:30px;padding-left:30px;padding-right:30px\">\n"
                    + "                                                                    <a target=\"_blank\" href=\"#\"\n"
                    + "                                                                        style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#ffffff;font-size:18px\">Nosotros\n"
                    + "                                                                        estamos listos para ayudar&nbsp;</a></td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </table>\n"
                    + "                                                    </td>\n"
                    + "                                                </tr>\n"
                    + "                                            </table>\n"
                    + "                                        </td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                            </td>\n"
                    + "                        </tr>\n"
                    + "                    </table>\n"
                    + "                    <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer\" align=\"center\"\n"
                    + "                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top\">\n"
                    + "                        <tr style=\"border-collapse:collapse\">\n"
                    + "                            <td align=\"center\" style=\"padding:0;Margin:0\">\n"
                    + "                                <table class=\"es-footer-body\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\n"
                    + "                                    style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px\">\n"
                    + "                                    <tr style=\"border-collapse:collapse\">\n"
                    + "                                        <td align=\"left\"\n"
                    + "                                            style=\"Margin:0;padding-top:30px;padding-bottom:30px;padding-left:30px;padding-right:30px\">\n"
                    + "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                <tr style=\"border-collapse:collapse\">\n"
                    + "                                                    <td valign=\"top\" align=\"center\"\n"
                    + "                                                        style=\"padding:0;Margin:0;width:540px\">\n"
                    + "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                            role=\"presentation\"\n"
                    + "                                                            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td align=\"left\" style=\"padding:0;Margin:0\">\n"
                    + "                                                                    <p\n"
                    + "                                                                        style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;line-height:21px;color:#111111;font-size:14px\">\n"
                    + "                                                                        <strong>Panel de control - Recuperaci&oacute;n -\n"
                    + "                                                                            Ayuda</strong></p>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td align=\"left\"\n"
                    + "                                                                    style=\"padding:0;Margin:0;padding-top:25px\">\n"
                    + "                                                                    <p\n"
                    + "                                                                        style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;line-height:21px;color:#666666;font-size:14px\">\n"
                    + "                                                                        Recibi&oacute; este correo electr&oacute;nico porque acaba de\n"
                    + "                                                                        olvidar su contrase&ntilde;a en nuestra web. Si se ve\n"
                    + "                                                                        raro,&nbsp;<strong><a target=\"_blank\"\n"
                    + "                                                                                href=\"#\"\n"
                    + "                                                                                style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#111111;font-size:14px\">visual&iacute;zalo\n"
                    + "                                                                                en la\n"
                    + "                                                                                aplicación&nbsp;</a>&nbsp;</strong>.</p>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td align=\"left\"\n"
                    + "                                                                    style=\"padding:0;Margin:0;padding-top:25px\">\n"
                    + "                                                                    <p\n"
                    + "                                                                        style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:lato, 'helvetica neue', helvetica, arial, sans-serif;line-height:21px;color:#666666;font-size:14px\">\n"
                    + "                                                                        Si estos correos electr&oacute;nicos se vuelven\n"
                    + "                                                                        molestos, no dude en&nbsp;<strong><a\n"
                    + "                                                                                target=\"_blank\"\n"
                    + "                                                                                href=\"https://my.stripo.email/cabinet/\"\n"
                    + "                                                                                style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#111111;font-size:14px\">darse\n"
                    + "                                                                                de baja</a></strong>.</p>\n"
                    + "                                                                </td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </table>\n"
                    + "                                                    </td>\n"
                    + "                                                </tr>\n"
                    + "                                            </table>\n"
                    + "                                        </td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                            </td>\n"
                    + "                        </tr>\n"
                    + "                    </table>\n"
                    + "                    <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\n"
                    + "                        style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\n"
                    + "                        <tr style=\"border-collapse:collapse\">\n"
                    + "                            <td align=\"center\" style=\"padding:0;Margin:0\">\n"
                    + "                                <table class=\"es-content-body\"\n"
                    + "                                    style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px\"\n"
                    + "                                    cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"
                    + "                                    <tr style=\"border-collapse:collapse\">\n"
                    + "                                        <td align=\"left\"\n"
                    + "                                            style=\"Margin:0;padding-left:20px;padding-right:20px;padding-top:30px;padding-bottom:30px\">\n"
                    + "                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                <tr style=\"border-collapse:collapse\">\n"
                    + "                                                    <td valign=\"top\" align=\"center\"\n"
                    + "                                                        style=\"padding:0;Margin:0;width:560px\">\n"
                    + "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                                            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                    + "                                                            <tr style=\"border-collapse:collapse\">\n"
                    + "                                                                <td align=\"center\"\n"
                    + "                                                                    style=\"padding:0;Margin:0;display:none\"></td>\n"
                    + "                                                            </tr>\n"
                    + "                                                        </table>\n"
                    + "                                                    </td>\n"
                    + "                                                </tr>\n"
                    + "                                            </table>\n"
                    + "                                        </td>\n"
                    + "                                    </tr>\n"
                    + "                                </table>\n"
                    + "                            </td>\n"
                    + "                        </tr>\n"
                    + "                    </table>\n"
                    + "                </td>\n"
                    + "            </tr>\n"
                    + "        </table>\n"
                    + "    </div>\n"
                    + "</body>\n"
                    + "\n"
                    + "</html>";
        }

        Session sesion = Session.getInstance(props, new jakarta.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(props.getProperty("username"), props.getProperty("password"));
            }
        });

        Message mensaje = new MimeMessage(sesion);
        mensaje.setFrom(new InternetAddress(props.getProperty("from")));
        mensaje.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
        mensaje.setSubject(subject);

        MimeMultipart multipart = new MimeMultipart("related");

        BodyPart messageBodyPart = new MimeBodyPart();
        messageBodyPart.setContent(content, "text/html");
        multipart.addBodyPart(messageBodyPart);

        messageBodyPart = new MimeBodyPart();
        DataSource fds = new FileDataSource("src/Iconos/ICONO.png");

        messageBodyPart.setDataHandler(new DataHandler(fds));
        messageBodyPart.setHeader("Content-ID", "<image>");
        multipart.addBodyPart(messageBodyPart);

        mensaje.setContent(multipart);

        Transport.send(mensaje);
    }

}
